### PR TITLE
DefaultDevice - D-Pointer implementation

### PR DESCRIPTION
**Pull request by pawel-soja**
Hi!

A little cleaned up.

- D-Pointer implementation for the DefaultDevice class
- Add defineProperty function instead of defineXXX
- Access to POLLMS via getters/setters.

### CODE REVIEW

**Comment by pawel-soja** [comment]
A bit problematic that DefaultDevice had POLLMS and some classes used their own variable with the same name.
Where POLLMS is obscured, I used the name POLLMS_OVERRIDE.

I have not delved into this mechanism, but I can see that it repeats itself a lot.

**Comment by knro** [comment]
Thanks! Do we need a similar PR for 3rdparty repo? Otherwise, all the drivers would break over there.

**Comment by knro** [comment]
Ok, again I stand corrected. The drivers are working fine in 3rd party repo, just need a similar update to bring all in line.

**Comment by knro** [comment]
all drivers should use setters/getters for POLLMS now

**Comment by pawel-soja** [comment]
Yes, I have added temporary access to keep it compatible.

I will make changes in 3rd if a new version of DefaultDevice is available there. I understand that if I do it now, the tests will crash?

**Comment by knro** [comment]
If you're talking about CI tests, unfortunately, we couldn't figure out how to implement them for 3rd party repo. The idea is that it should be built against the latest libindi for commits pushed to master. This required creating a docker container to fetch the latest nightly build from the PPA. However, it never materialized and not sure if there is a better way to run CIs on the 3rd part repo.

**Comment by pawel-soja** [comment]
I took a look at what is currently being done. It looks pretty decent. Better any tests than none.
Currently it is enough to run circleci for 3rd-indi or did I miss something?
There is a warning on the warning in this project :)

One more thing, I would like to make sure, how is the PPA update currently being uploaded?

**Comment by knro** [comment]
There is no proper Circle CI integration yet for the INDI 3rd party repo :(

The PPA is built automatically nightly from Canonical Launchpad service.

**Pull request merged**
