### PR TITLE
Starbook 0.3

### PR DESCRIPTION
**Pull request by not7cd**
Main change in this patch is custom connection plugin and command interface.
I'm taking away much of unneeded connection handling from logic inside `Starbook` class.
Code is more bloated but hopefully more testable and safe. This is also preparation for more intelligent state handling. With knowledge of current Starbook state, we can prevent some errors and inform user. This should streamline initial connection where any wrong command can put Starbook into a _bad state_.

I need assistance with `Connection::Curl`, I can't get `saveConfig()` and `loadConfig()` working.

### CODE REVIEW

**Comment by knro** [comment]
That's the good way to do it!

What issues are you having with load and save Config?

**Comment by not7cd** [comment]
```
/home/not7cd/Workspace/indi/3rdparty/indi-starbook/connectioncurl.cpp: In member function ‘virtual bool Connection::Curl::Connect()’:
/home/not7cd/Workspace/indi/3rdparty/indi-starbook/connectioncurl.cpp:51:56: error: ‘virtual bool INDI::DefaultDevice::saveConfig(bool, const char*)’ is protected within this context
             m_Device->saveConfig(true, "DEVICE_ADDRESS");
                                                        ^
In file included from /usr/include/libindi/inditelescope.h:21:0,
                 from /home/not7cd/Workspace/indi/3rdparty/indi-starbook/connectioncurl.h:11,
                 from /home/not7cd/Workspace/indi/3rdparty/indi-starbook/connectioncurl.cpp:5:
/usr/include/libindi/defaultdevice.h:332:18: note: declared protected here
     virtual bool saveConfig(bool silent = false, const char *property = nullptr);
                  ^~~~~~~~~~
/home/not7cd/Workspace/indi/3rdparty/indi-starbook/connectioncurl.cpp: In member function ‘virtual void Connection::Curl::Activated()’:
/home/not7cd/Workspace/indi/3rdparty/indi-starbook/connectioncurl.cpp:72:52: error: ‘virtual bool INDI::DefaultDevice::loadConfig(bool, const char*)’ is protected within this context
         m_Device->loadConfig(true, "DEVICE_ADDRESS");
                                                    ^
In file included from /usr/include/libindi/inditelescope.h:21:0,
                 from /home/not7cd/Workspace/indi/3rdparty/indi-starbook/connectioncurl.h:11,
                 from /home/not7cd/Workspace/indi/3rdparty/indi-starbook/connectioncurl.cpp:5:
/usr/include/libindi/defaultdevice.h:323:18: note: declared protected here
     virtual bool loadConfig(bool silent = false, const char *property = nullptr);
                  ^~~~~~~~~~
```
This is problem with default device class. I don't know why it works with `Connection::TCP`. Shouldn't these methods be public if reference to device is passed here and there?

**Comment by knro** [comment]
Few more CI errors to attend to.

**Comment by knro** [comment]
I added preliminary documented based on EQMod documentation here: https://indilib.org/devices/telescopes/vixen/vixen-starbook.html

You have permissions to edit the page and change information as necessary. Screenshots for all the tabs will be needed of course. The screenshots need to go images/devices/vixen. If you have trouble uploading them, just email me the images and I'll upload them.

Driver documentation is very important, especially for new users! so please put there everything a new user needs to know about connecting to the mount and utilizing it.

**Comment by knro** [comment]
Also, will merge this. Can you please update the documentation?

**Pull request merged**
