### PR TITLE
New Focuser Driver MyFocuserPro2

### PR DESCRIPTION
**Pull request by ajt68**
New driver for MyFocuserPro2 (my 2nd pull reuest ever, this time AFTER pushing my chnages!!!)

### CODE REVIEW

**Comment by knro** [comment]
Thanks! It appears there is small issue regarding unused field in the class. Check the CI error for more details. You can just commit to this PR, no need to open a new one.

**Comment by knro** [comment]
Looks like you pushed your build directory as well

**Comment by ajt68** [comment]
> Looks like you pushed your build directory as well

So does that mean I have to do another commit, but this time without using "git add.", and somehow just adding the change files (which is what I thought "git add ." was doing,, this is my first time using git!)

Is this also the correct way of communicating regarding me not knowing what I am doing? Or should this be opened as a topic in the Development forum for Indi?

**Comment by knro** [comment]
Great thanks! The last bit required is the driver documentation. Please submit the screenshots + text to be like the following: https://indilib.org/devices/focusers/focuslynx.html

Here is the documentation template you can use: https://github.com/indilib/indi/tree/master/libindi/drivers

Use the focuser template and add your driver information to it along with text and images.

**Comment by knro** [comment]
Hello any update on the documentation?

**Comment by ajt68** [comment]
> Hello any update on the documentation?
Attached documentation, not sure how I am supposed to format it, or supply the meta data, so have just added it to the top of the html file. Also the guide states all images must be jpg, so I converted mine from png, but then saw that png is used in other focuser pages!!!. There is also an image of the focuser in question supplied by the original designer of the focuser. I'm guessing I can't edit the documentation, and just submit edits through this mechanism?
main_control
myFocuserPro2
options
presets

connection

**Comment by knro** [comment]
Check the template here: https://github.com/indilib/indi/blob/master/libindi/drivers/README.md

Then just include the text file + images and zip them in an attachment. Include the metadata in the same text file.

**Comment by ajt68** [comment]
[myfocuserpro2.zip](https://github.com/indilib/indi/files/3616309/myfocuserpro2.zip)

**Comment by knro** [comment]
Great work Alan! All is looking good and I just uploaded the listing here:

https://indilib.org/devices/focusers/myfocuser-pro-2.html

**Comment by ajt68** [comment]
HI, I have found a problem in a link on the device drive page for
myFocuserPro2

<a href="https://github.com/DeepSkyDad/AF1">

should be replaced with

<a href="https://sourceforge.net/projects/arduinoascomfocuserpro2diy/">

Regards, Alan.

**Comment by knro** [comment]
It's done. Can you please take a look at the reported issues here?

https://www.indilib.org/forum/focusers-filter-wheels/4802-myfocuserpro-or-myfocuserpro2-and-indi.html?start=24#43906

**Pull request merged**
