### PR TITLE
Bugfix for V4L2 odd crop dimensions

### PR DESCRIPTION
**Pull request by TallFurryMan**
This PR is expected to fix the issue discussed at https://www.indilib.org/forum/ccds-dslrs/3180-v4l2-subframe-error-with-phd2.html. A regular issue had to be created, but was not. I'll open one to describe the intent.

### CODE REVIEW

**Comment by TallFurryMan** [comment]
Don't merge right now, PR has conflicts. It is a preliminary, I'll update.

**Comment by TallFurryMan** [comment]
I still need to test this on a real setup. Please standby.
I'm also trying to run a coverity scan, still not working.

**Comment by not7cd** [comment]
You can use Draft functionality to prevent maintainer from merging prematurely. It's quite new.
https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by knro** [comment]
What's the status for this PR?

**Comment by TallFurryMan** [comment]
Untested unfortunately. Got no time to verify on my DMK setup 😔 Works on my Logitech internal webcam at least.

**Comment by TallFurryMan** [comment]
Feature is basic-tested OK on my DMK setup, but I have seen strange white frames sometimes (zero frames). This was with the shutter closed, and was not reproduced for exposures larger than 5 seconds.
I will test again on the next clear night with PHD2.

**Comment by TallFurryMan** [comment]
White frame = zero frame because of the FITS viewer stretching :)

**Comment by TallFurryMan** [comment]
Works great on my side.

It seems this improved my guiding accuracy on my low-end system and wifi, though I got unrelated differential rotation issues when testing with 1200-second exposures.

This would close #894 if merged.

**Pull request merged**
