### PR TITLE
Prevent Portage errors while installing on Gentoo

### PR DESCRIPTION
**Pull request by Ctibor**
This fixes sandbox ACCESS_VIOLATION errors while installing libqhy, libsbig and libinovasdk on Gentoo. Symlinks to .so are created in working directory instead of live system.

### CODE REVIEW

**Comment by jochym** [comment]
@Ctibor please check "maintainers can edit" on the right hand side of this PR page - that way we can make corrections to the PR.

**Comment by Ctibor** [comment]
@jochym I see it checked in other words this option is enabled.

**Comment by jochym** [comment]
Thanks.

**Comment by knro** [comment]
You need to rebase and submit a new PR. Also how is this going to work exactly? Make .so in build directory then copy them over?

**Pull request closed without merging**
