### PR TITLE
Enable saving/loading backlash steps and fix motor type select

### PR DESCRIPTION
**Pull request by tstibor**

### CODE REVIEW

**Comment by knro** [comment]
Thank you Thomas. I think I merged your previous PR maybe too early? Is this ready to land?

**Comment by tstibor** [comment]
Hello Jasem,

the previously merged PR (https://github.com/indilib/indi/commit/7e80b997d0c2993b51e32fbc03529fb63fd2e617) is actually also bundled in this PR (https://github.com/indilib/indi/pull/1054/commits/ed8b3dcd82a25e02aa3fc43487d7117ed99d041a),
don't know why.  The new PR (https://github.com/indilib/indi/pull/1054/commits/8f25986cc5cd7c69fb950b4ec844325b214327d1) enables saving focus backlash value and 
makes sure, that when backlash value is 0, one can still enable backlash compensation with a value > 0,

**Comment by tstibor** [comment]
If this is too messy, I can disentangle the latest PR and send a new PR which contains https://github.com/indilib/indi/pull/1054/commits/8f25986cc5cd7c69fb950b4ec844325b214327d1

**Comment by knro** [comment]
Sure, go ahead.

**Pull request closed without merging**
