### PR TITLE
Add button for custom resolution in simulator CCD

### PR DESCRIPTION
**Pull request by escribana**
Add button for custom resolution to reestablish the possibility to work with the resolution defined in simulator config.

### CODE REVIEW

**Comment by knro** [comment]
So when custom is selected, it should use whatever is in simulator config? this is not implemented yet.

**Comment by escribana** [comment]
I do not understand: I tested with EKOS and it works!
But there is indeed  little problem insofar the image settings are not set immediately in the Image Settings tab of the INDI Control Panel. Do you address this with your comment?

**Comment by knro** [comment]
I guess what I mean is this: if you select custom, then what happens? how is the resolution set/updated?

**Comment by escribana** [comment]
The problem arose with 3.7.2. I could not use my custom resolution in Simulator Config anymore, since it always jumped back to the preset resolution 1280x1024. With this "Custom" button this resolution is preserved again. So is "Config" a better designation for the button?

**Pull request merged**
