### PR TITLE
Fixes and adds for indidetector

### PR DESCRIPTION
**Pull request by iliaplatone**
I added a new tutorial for indidetector and fixed a bug on blob generated fits for this interface.

### CODE REVIEW

**Comment by knro** [comment]
I don't see simulator detector file in there?

**Comment by iliaplatone** [comment]
finished.

**Comment by knro** [comment]
does it make sense for detectors to have shutters? coolers?

**Comment by iliaplatone** [comment]
These capabilities are for photon detectors, which are 1-px very fast CCDs essentially

**Pull request merged**
