### PR TITLE
Added RA/DEC guide speed 

### PR DESCRIPTION
**Pull request by amendolajamie**
Added RA/DEC guide speed with properties GUIDE_RATE_WE and GUIDE_RATE_NS and changed name of property vector
to GUIDE_RATE. This fixes PHD reporting "Unknown" for guide rate.
    
+ Some general cleanup.

### CODE REVIEW

**Comment by knro** [comment]
Can you please rebase? there are some merge conflicts with the upstream version.

**Comment by knro** [comment]
@amendolajamie After the rebase is done, perhaps it is time to update to the [driver documentation](https://indilib.org/telescopes/losmandy.html) to explain these functions to prospective users?

**Comment by amendolajamie** [comment]
Sure I'll do that as well.

**Comment by amendolajamie** [comment]
Hi Jasem,

So, I'm starting in on this now. I'm not sure how I can update the
documentation. It seems to be a webpage and I don't believe that I have
access to it. How do I update the documentation?

**Comment by knro** [comment]
Either sign up for an account on indilib.org and then we'll grant you access, or simply add the content here in the response or by attaching a file and we'll take care of it.

**Comment by amendolajamie** [comment]
OH, I do have an account: amendolajamie Maybe you can add permission and
point me to where I can edit it.

Jamie

**Comment by knro** [comment]
Thanks, you've been added to "Developer Editor" group now so if you go to the article, you should see an Edit button.

Can you please rebase this PR?

**Comment by knro** [comment]
You didn't not rebase correctly, please try again as you included more files.

**Comment by amendolajamie** [comment]
I'll do that. Please forgive me I'm a recovering perforce user.

So just to be clear, is the issue that commits are duplicated? Looking through gitk I see some duplicates in my history. Will squashing those suffice?  

Should I squash the the ones marked below? 

00d541717eb8e9b405937aea60b715bca30df947
    Added RA/DEC guide speed with properties GUIDE_RATE_WE and GUIDE_RATE_NS and changed name of property vector
    to GUIDE_RATE. This fixes PHD reporting "Unknown" for guide rate.

**Squash -----------------------------------**
5933536e7cce59b1f569f328ecee0f278a3f90d6
    Added "enable pec at boot" switch, and a display for "current pec guiding speed"

**Squash -----------------------------------**
92fc68ff78a1eb386fe77923072bce3c892ecae8
    Add Servo Precision control

**Squash -----------------------------------**
1412a76571854d52634a6e5db9f4d17369037647
    Added RA/DEC guide speed with properties GUIDE_RATE_WE and GUIDE_RATE_NS and changed name of property vector
    to GUIDE_RATE. This fixes PHD reporting "Unknown" for guide rate.
 
25359f11371b964900a1af6e5ad98457cfc3b210
    Added "enable pec at boot" switch, and a display for "current pec guide speed" (#1685)

451b858199a1686c34e94549138fd00436f22b03
    Add Servo Precision control (#1683)

22451d6c15591c3451aaf325f38f19c547727049
    Adding some basic PEC status and control to lx200gemini (#1675)





I'm not sure what you mean by "included more files", did you meen commits?

**Comment by amendolajamie** [comment]
Thanks Jasem! 

I took a look at the documentation. I was able to select "edit", but could not seem to change the text in the "Description". Is there another permission that I need, or am I missing something? 

Another question -- There are some more changes that I'd like to put in. Namely I'd like to add the gemini 2 firmware version for display, but also to toggle on/off features based on the version. It may make sense to wait for those to be reviewed/committed before updating the documentation. What do you think?

**Pull request merged**
