### PR TITLE
Add polling fucntion

### PR DESCRIPTION
**Pull request by djibb**
Add a polling function to get state of spectrometer.

### CODE REVIEW

**Comment by knro** [comment]
You should use SetTimer(..) and then overwrite TimerHit(...) function to do polling like in other INDI drivers.

**Comment by djibb** [comment]
polling function is only internal. It's used only inside driver to discuss
at connection and had no impact on driver yet.
May be the release is too early.
The idea is to use this function to set what you say.


Le ven. 27 juil. 2018 à 15:14, Jasem Mutlaq <notifications@github.com> a
écrit :

**Comment by knro** [comment]
You can use setDefaultPollingPeriod(250) for example and then TimerHit() would be called every 250ms. No need to implement additional polling property since it is built into all drivers.

**Comment by knro** [comment]
Hello, any update on this PR?

**Comment by djibb** [comment]
Hi.

Not for the moment.

Stash it. I will comme back later.

Le jeu. 2 août 2018 à 07:49, Jasem Mutlaq <notifications@github.com> a
écrit :

**Comment by knro** [comment]
I think you need to rebase and I'm not seeing polling, but you changed name to SPOX?

**Comment by djibb** [comment]
Hi,

close this pull request.
i will request when ready.

yes, as shelyak ask me, i renamed alpy driver to SPOX driver, as spox
module are lhires II, lisa and alpy compatible.

JB

Le ven. 7 sept. 2018 à 10:09, Jasem Mutlaq <notifications@github.com> a
écrit :

**Comment by knro** [comment]
Ok great. will wait for the next PR.

**Pull request closed without merging**
