### PR TITLE
Fix XML Escape

### PR DESCRIPTION
**Pull request by pawel-soja**
Hi!

I moved the XML build to a separate file, indiuserio.c.
Changes:
- A secure XML leak (https://github.com/indilib/indi/issues/1412)
- Fewer calls to printf
- Fewer intermediary buffers
- Single function implementations

To minimize the number of buffers, and not to repeat the implementation for streams, sockets etc, I created a 'userio' (User Input-Output). Currently, it is an introduction to further development.

With a userio, you can write a universal code (INDI Style):
```cpp
void IUUserIOTextContext(const userio *io, void *user, const ITextVectorProperty *tvp)
{
    for (int i = 0; i < tvp->ntp; i++)
    {
        IText *tp = &tvp->tp[i];
        userio_prints    (io, user, "  <oneText name='");
        userio_xml_escape(io, user, tp->name);
        userio_prints    (io, user, "'>\n");
        userio_prints    (io, user, "      ");
        userio_xml_escape(io, user, tp->text ? tp->text : "");
        userio_prints    (io, user, "\n");
        userio_prints    (io, user, "  </oneText>\n");
    }
}
```

Now, you can define what functions are to be triggered:
```cpp
userio ioBaseClient;
/* ... */
ioBaseClient.write = [](void *user, const void * ptr, size_t count) -> size_t
{
    BaseClient *self = static_cast<BaseClient *>(user);
    return net_write(self->sockfd, ptr, count);
};

ioBaseClient.vprintf = [](void *user, const char * format, va_list ap) -> int
{
    BaseClient *self = static_cast<BaseClient *>(user);
    char message[MAXRBUF];
    vsnprintf(message, MAXRBUF, format, ap);
    return net_write(self->sockfd, message, strlen(message));
};
/* ... */
```

And finally, calling:
```cpp
FILE *fp;
/* ... */

IUUserIONewNumber(userio_file(), fp, nvp); // to file
IUUserIONewNumber(userio_file(), stdout, nvp); // to stdout
IUUserIONewNumber(&ioBaseClient, this, nvp); // send via BaseClient

```

Now I can make a button with any name!

```cpp
IUFillSwitchVector(
    &RainSP, RainS, 2, getDeviceName(),
    "Control \"'& &amp;lt; ", // brutal test
    "", MAIN_CONTROL_TAB, IP_RW, ISR_1OFMANY, 0,
    IPS_IDLE
);
```
image

On days, I'll add the rest.
@knro will you take a look?
You will always catch something ;)

### CODE REVIEW

**Comment by pawel-soja** [comment]
With double unescape, it's probably a matter of sequence. I will find it.

**Comment by knro** [comment]
Thank you! This is awesome and would certainly pave the way for a more generic approach. Now gotta put it to the test

**Comment by pawel-soja** [comment]
I got it!
All mechanisms work, so there are correct names underneath. So I started looking in the way it was displayed.

```cpp
/* build widgets for property pp using info in root.
 */
void INDI_P::initGUI()
{
    /* ... */
    labelW->setFrameShape(QFrame::Box);
    labelW->setFrameShadow(QFrame::Sunken);
    labelW->setMargin(2);
    labelW->setFixedWidth(PROPERTY_LABEL_WIDTH * KStars::Instance()->devicePixelRatio());
    labelW->setTextFormat(Qt::RichText);
    labelW->setAlignment(Qt::AlignVCenter | Qt::AlignLeft);
    labelW->setWordWrap(true);
    /* ... */
}
```

https://github.com/KDE/kstars/blob/1c964bf33b51cfe0b5efba3a78d92d4cae8b1293/kstars/indi/indiproperty.cpp#L128

Example:
image

**Comment by knro** [comment]
Right, that what I suspected as well. However, I don't think we should be using PlainText, it should remain as rich text.

**Comment by pawel-soja** [comment]
It has to be mentioned somewhere because when using the <> characters, some of the message may disappear.

@knro Qt version working?

KStars clientmanager.h
```cpp
#if INDI_VERSION_MAJOR >= 1 && INDI_VERSION_MINOR >= 5
        virtual void newUniversalMessage(std::string message) override;
#endif
```
But it is absent in baseclientqt.
I also gets deadlocks on blocking connections.
```
Qt: Dead lock detected while activating a BlockingQueuedConnection: Sender is ClientManager(0x5611aa6c8370), receiver is GUIManager(0x5611abcd30f0)
```

**Comment by pawel-soja** [comment]
So rich text. I will paste links :)
image

**Comment by pawel-soja** [comment]
Hi @knro, I tested. I think it is OK.

**Comment by knro** [comment]
Sending links might actually be a good idea for some items :D but hopefully this won't get abused.

**Pull request merged**
