### PR TITLE
[indi_script_dome and indi_script_telescope] replace tmpnam with mkstemp, improve error reporting, check script existence before execvp

### PR DESCRIPTION
**Pull request by d33psky**

### CODE REVIEW

**Comment by knro** [comment]
Thanks! Can you please apply the same to telescope_script as well since it suffers from the same issue?

**Comment by d33psky** [comment]
ah I see. yes. will do. Do you want that in this same branch ?

**Comment by knro** [comment]
Sure, same PR.

**Comment by d33psky** [comment]
similar changes to indi_script_telescope added

**Comment by knro** [comment]
yay finally no warnings! THANKS A ALOT!

**Pull request merged**
