### PR TITLE
Nighscape 8300 Driver/Optec IFW supports TCP/IP

### PR DESCRIPTION
**Pull request by dirkenstein**
new pull request to replace yesterday's as this failed a number of compile options due to D2XX being mandatory.

New version will now build as long as at least libftdi1 and libusb1 are available.

Also removed serial support by default as it doesn't work (kernel ftdi_sio driver can't handle bulk data well).

### CODE REVIEW

**Comment by knro** [comment]
@jochym What's going on with the CI?

**Comment by knro** [comment]
Can you please rebase to fix the conflict above? Also, I think we need to provide documentation for this over at indilib.org (e.g. http://indilib.org/devices/ccds/apogee-ccd.html)

**Comment by knro** [comment]
Great work! The documentation + screenshots would be greatly appreciated!!

**Comment by dirkenstein** [comment]
Is there a standard format for the docs at indilib.org?
I guess you want ekos screenshots. Do you have the source for the apogee doc  page so i can edit it appropriately.

I've added the standard text documents in the source dir and pushed them.

**Comment by knro** [comment]
Do you have a user account on INDI Library website? I can give you permissions to create a new listing.

**Comment by dirkenstein** [comment]
My forum account is dirkn.

**Comment by knro** [comment]
Ok you have permission now. You can now edit this --> http://indilib.org/devices/ccds/celestron-nightscape-8300.html

**Comment by dirkenstein** [comment]
Edits completed, hopefully sufficient for the purpose.

**Comment by knro** [comment]
Wow that was fast! Thanks a lot! I just added an image. I'll try to prepare the 3rd party release today.

**Comment by knro** [comment]
Ok I just pushed few improvements to the code. But I'm not sure what drop_root_privileges() is for? Is the driver required to start as root to set it as high priority (renice to -20) which would require root privileges?

**Comment by dirkenstein** [comment]
Hi Jasem,

The drop_root_privileges is only needed if you run the driver setuid root. It's optional, and has no effect on the driver if run as a normal user. 

I don't provide instructions for doing it because it's inherently a bad idea, but it may be needed in two scenarios:

a) setting up your driver to have access to the USB devices without root needs some udev scripts on Linux. I can provide these if required so the usb device  for the nightscape is added to group 'usb'. You add your indi user to that group and it has access to the device.

b) Setting priority to -20 helps with the USB stability on my mac. It may not have as much affect for everyone. You can't renice to -20 without root privileges or some really complicated /etc/limits settings.

**Comment by knro** [comment]
Excellent, do you have the VID:PID for the camera so I can add a udev rule at least for Linux users?

**Comment by dirkenstein** [comment]
This rule works

SUBSYSTEMS=="usb", ATTRS{product}=="Nightscape CCD Camera", GROUP="usb"

**Comment by dirkenstein** [comment]
VID and PID 👍 
  int vid = 0x19b4;
    int pid = 0x0065;

**Pull request merged**
