### PR TITLE
DreamFocuser Driver

### PR DESCRIPTION
**Pull request by pidlug**
This is a driver for DreamFocuser focuser, used by many people in Poland. Here is more information (in polish unfortunately): https://astropolis.pl/topic/53348-dreamfocuser/

### CODE REVIEW

**Comment by knro** [comment]
Can we get documentation for INDI website please?

**Comment by pidlug** [comment]
Hi Jasem, thanks for merging. I will prepare something. Could you point me to the best example how you would like it to look like?

**Comment by knro** [comment]
Absolutely. I think I will add this template for documentation for some drivers to the repo.

**Comment by knro** [comment]
Ok please check here: https://github.com/indilib/indi/tree/master/libindi/drivers

Let me know if you have any questions!

**Comment by pidlug** [comment]
Hi Jasem, here is the doc.
[dreamfocuser_doc.zip](https://github.com/indilib/indi/files/3077376/dreamfocuser_doc.zip)

**Pull request merged**
