### PR TITLE
Add Driver for Esatto with Arco (goto, abort, sync, cal)

### PR DESCRIPTION
**Pull request by ChristianHen**
Add new Driver for Esatto-Arco unit based on the existing Esatto / Sestosenso-Driver

### CODE REVIEW

**Comment by knro** [comment]
Thanks, I think you should move this to rotator directly unless it's BOTH a focuser + rotator? Isn't this for the Arco 2" and 3" ?

**Comment by ChristianHen** [comment]
Ist is both, Focuser and Rotator.

**Comment by knro** [comment]
Please check CI build failure. Also, where all functionalities tested? everything in the INDI control panel is confirmed to function correctly?

**Comment by ChristianHen** [comment]
I changed one line in the .cpp ( if(!busy==0) --> if(!(busy==0) ) then the MacOs Workflow ran successfully in my repo.

PyIndi and Docker failed. Docker-Workflow claims that the repo-name must be lower case. I dont' know what to do about these two workflows.

**Comment by ChristianHen** [comment]
I created a second github-account with a username that is completely lower case. There the docker-workflow runs successfully.
So dokker, macOS and Linux are ok.

**Comment by knro** [comment]
I see that Arco can be used separately... so this driver required a combination of Essato + Arco together I presume?

**Comment by ChristianHen** [comment]
Correct

**Comment by spacekitteh** [comment]
> Really.. okay thanks for clarifying this.. so Arco can never be used standalone??

Yeah, it's extreme vendor lock-in.

**Pull request merged**
