### PR TITLE
Add Skywatcher Alt-Az Simple mount driver

### PR DESCRIPTION
**Pull request by kecsap**
It is "forked" Skywatcher Alt-Az mount driver. Changes:
- Removed alignment subsystem codes
- Alt/Az <-> Ra/Dec conversions are based on pure libnova
- Supporting wedge and "EQ wedge" (placing the Alt/Az mount on the top of an EQ mount) modes
- Guiding support in wedge/EQ wedge modes.

### CODE REVIEW

**Comment by knro** [comment]
The name SW AltAz is confusing I think to end-users.

**Comment by kecsap** [comment]
What name do you prefer? Can we just ditch the old driver? It will be anyway in git history and the alignment subsystem does not give any benefit in performance for these cheap Alt/Az mounts. I was able to do the same exposure duration with the old and the refactored driver.

**Comment by knro** [comment]
Does your specific mount have a brand? Maybe use that.

**Comment by kecsap** [comment]
This driver is generic Alt/Az driver like the old one. Now it was tested with Skywatcher Merlin and Skywatcher Virtuoso.

**Comment by knro** [comment]
You never know maybe there are users out there who uses it. So think of a name but let's keep the existing one.

**Comment by kecsap** [comment]
"Skywatcher Alt/Az Reborn"?

**Comment by knro** [comment]
haha well I don't think we can use that. Maybe SkyWatcher Alt-Az Wedge?

**Pull request merged**
