### PR TITLE
Update to latest ZWO provided SDK and add support for newer cameras.

### PR DESCRIPTION
**Pull request by goodwink**
I've pulled in the latest SDK from ZWO and added support for the following cameras:

- ASI1600M(M|C)(-Cool)?
- ASI290M(M|C)(-Cool)?

### CODE REVIEW

**Comment by goodwink** [comment]
I have only tested this on linux x64, but the libraries are provided upstream and I haven't changed any other code, so it shouldn't make any difference.

**Comment by knro** [comment]
I believe ZWO is working on fixing an issue on Raspberry PI as the image is not downloaded on full native resolution via libusb. Is this issue fixed with this binary? Also please make sure that all the text files have unix EOL. use dos2unix tool to convert all files to unix end-of-line first.

**Comment by goodwink** [comment]
I have not tested on arm, I will have to check with Sam.  I'll run dos2unix on ZWO's header file.

**Comment by knro** [comment]
ZWO already submitted a PR.

**Comment by goodwink** [comment]
@knro that PR did not update the udev rules, so the new cameras will only be usable by root.

**Comment by knro** [comment]
Please submit a new PR for the udev rules.

**Comment by knro** [comment]
Nevermind, I applied the diff to the udev rules.

**Pull request closed without merging**
