### PR TITLE
Fix a bug in Celestron protocol and reduce code verbosity

### PR DESCRIPTION
**Pull request by juanmb**
- I fixed a bug that happened when parsing responses from celestron mounts: `tty_read_section` doesn't work with some non-ASCII packets.
- I added a method for checking the firmware version that removes code duplication.
- New logging macros reduce the code verbosity an avoid many long lines.

### CODE REVIEW

**Comment by knro** [comment]
Excellent work! Do you also have tests pending?

**Comment by juanmb** [comment]
Thank you!
Yes, I started working in some tests, but I haven't finished them. I will add them in the next commit.

**Comment by knro** [comment]
Please also check this: https://github.com/indilib/indi/pull/475

**Comment by juanmb** [comment]
Yes, #475 is already fixed in this PR

**Comment by knro** [comment]
I'll merge this now, please open another PR for the tests since these changes are high-priority now.

**Comment by knro** [comment]
Can you please take a look at this?

http://indilib.org/forum/mounts/2926-commit-5-and-20-days-aago-breaks-celestron-avx.html#21874

**Comment by juanmb** [comment]
Of course!

**Comment by knro** [comment]
and there is another one here: http://indilib.org/forum/ekos/2922-slew-to-target-failed.html#21922

Is the AVX issue resolved?? or not merged yet?

**Comment by juanmb** [comment]
It should be fixed in my repo. I asked the user if he could check it, but I
still have not received an answer.
I can make a pull request, anyway. This is the commit:
https://github.com/juanmb/indi/commit/1c1a0c59afe848ade692d006b619704adecfc00d

BTW, the tests are not running in CircleCI because gtest and gmock
libraries are not installed in the Docker containers. I will try to fix it.

**Pull request merged**
