### PR TITLE
V4L2 integer menus

### PR DESCRIPTION
**Pull request by geehalel**
I've added V4L2 integer menus (specifically for the rpi camera).
Also try to stop capturing/recording when device is disconnected.
Finally check if a V4L2 control is mutable before setting it (it can be grabbed, inactive,....)

### CODE REVIEW

**Comment by TallFurryMan** [comment]
Are you able to reproduce #242 with your setup? There's a debug log causing a segfault somewhere in check_device.

**Comment by geehalel** [comment]
I don't have a raspberry camera and the ones I use were working with a
quiet recent version of libindi.
I would suggest to modify Indi::Logger to test for null string as I think
the raspberry driver may not fill every fields (cap.driver, cap.bus_info or
input names for instance).

**Comment by TallFurryMan** [comment]
I think a null string will be properly handled as "(null)". Might be a non-init string in an out-of-bounds structure record instead. I'll slice that big function into smaller ones and the issue should pop up while refactoring. Thanks :)

**Comment by geehalel** [comment]
Yes, you're right. Reading the v4l2 doc:
"Storing strings in fixed sized arrays is bad practice but unavoidable
here. Drivers and applications should take precautions to never read or
write beyond the end of the array and to make sure the strings are properly
NUL-terminated."
suggests to test every string returned from v4l2 drivers...

**Pull request merged**
