### PR TITLE
Add Starbook mount controller driver 0.1

### PR DESCRIPTION
**Pull request by not7cd**
This PR adds basic support for Vixen Starbook.
Starbook is a handheld controller. It is discontinued and was used with New Atlux and Sphinx mounts.

As it's physical interface is ageing, there is a need to automate its operation.
Starbook has single LAN port and HTTP server capability. It can respond to high level commands.
Commands behaviour was reverse engineered and it's bad...

Nevertheless I have implemented basic capability to automate New Atlux mount with Starbook as middleman.

_References:_

1. http://enzerink.net/peter/blog/2008/06/28/ascom-star-book-driver
2. https://github.com/farhi/matlab-starbook
3. https://github.com/rbur004/rubytelescopeserver

### CODE REVIEW

**Comment by knro** [comment]
Great work! Can you please also submit documentation for us like the ones we have in the INDI website?

**Comment by not7cd** [comment]
I have added basic information how to operate this driver. I don't know how to install this with newest stable `indilib` for production use. More will come with newer versions.

**Comment by knro** [comment]
Let me know if your changes are ready for merging.

**Comment by not7cd** [comment]
This isn't hooked up to the main build, so I need support with that.

**Comment by knro** [comment]
It will be added with 3rd party, I'll merge and then manage 3rd party build.

**Pull request merged**
