### PR TITLE
ActiveFocuser driver release

### PR DESCRIPTION
**Pull request by AlvinFrey**
Here is my contribution to the indi repository by adding the INDI driver for the ActiveFocuser system (focuser for Mewlon-250CRS and CCA250).

You can download the driver informations for the website on this [link](http://www.takahashi-europe.com/support/softwares/activefocuser/driver-informations-indi.zip).

### CODE REVIEW

**Comment by knro** [comment]
Thank you Alvin! Do you mind submitting documentation for the driver for end users? Please follow the [Focuser Documentation Template](https://github.com/indilib/indi/tree/master/drivers#focusers).

We need screenshot for each tab and driver metadata so it can be added to [INDI Devices Hub](https://indilib.org/focusers.html).

You can submit everything in a zip file and I'll add it to the INDI website. Thank you again for your submission!

**Comment by AlvinFrey** [comment]
> Thank you Alvin! Do you mind submitting documentation for the driver for end users? Please follow the [Focuser Documentation Template](https://github.com/indilib/indi/tree/master/drivers#focusers).
> 
> We need screenshot for each tab and driver metadata so it can be added to [INDI Devices Hub](https://indilib.org/focusers.html).
> 
> You can submit everything in a zip file and I'll add it to the INDI website. Thank you again for your submission!

Thanks ! 

I already sent you the basic driver documentation, I edit those files and come back to you when they are ready !

**Comment by AlvinFrey** [comment]
Here is the updated version of the driver informations : [http://www.takahashi-europe.com/support/softwares/activefocuser/driver-informations-indi.zip](http://www.takahashi-europe.com/support/softwares/activefocuser/driver-informations-indi.zip)

I hope that this is fine for you !

**Comment by knro** [comment]
Thank you, it's been added now and merged as well! Great work Alvin.

**Comment by AnakChan** [comment]
Thank you Alvin for this driver! I've been waiting for this for a long time and I'm so happy to see you deliver on this!

**Pull request merged**
