### PR TITLE
ZWO AM5 Save home position in the mount

### PR DESCRIPTION
**Pull request by pawel-soja**

### CODE REVIEW

**Comment by knro** [comment]
Probably needs to be updated with #2090

**Comment by pawel-soja** [comment]
Yes, I see. I'm currently analyzing this pull request.

**Comment by knro** [comment]
Please update to be inline with latest master code

**Comment by pawel-soja** [comment]
The implementation has changed a lot. I'm creating a new branch and a pull request:
- https://github.com/indilib/indi/pull/2093

**Pull request closed without merging**
