### PR TITLE
Create issue template for bug reports

### PR DESCRIPTION
**Pull request by not7cd**
Looking at issues I can see an emerging pattern and lack of proper data to tackle some of the issues.

### CODE REVIEW

**Comment by knro** [comment]
Thanks!! We really need this!!

**Comment by knro** [comment]
Oppps.. looks I merged prematurely. Github expects this file where exactly? Because when I create a new issue, it's not loaded.

**Comment by not7cd** [comment]
It might be a case for legacy workflow. 
I think I have put this in the right place. New workflow should be available here:
https://help.github.com/en/articles/about-issue-and-pull-request-templates

**Comment by not7cd** [comment]
Because normal users can't add labels to issues, this template might not work. I need to look through examples again.

**Comment by knro** [comment]
I already added a couple of templates via the Github interface.

**Pull request merged**
