### PR TITLE
rbfocus driver intitial release

### PR DESCRIPTION
**Pull request by rbfocus**
Closed by mistake pull request resubmitted.

### CODE REVIEW

**Comment by knro** [comment]
THank you! Can you please also submit the documentation for this driver so it may be used in https://indilib.org/focusers.html ?

You can find a [focuser template](https://github.com/indilib/indi/tree/master/drivers) to get started with.

**Comment by rbfocus** [comment]
Sure, where should I upload the documentation?

**Comment by rbfocus** [comment]
Here is the documentation for the RB Focuser driver. thank you
[DriverInfo.zip](https://github.com/indilib/indi/files/5629209/DriverInfo.zip)
!!

**Comment by rbfocus** [comment]
Jasem, in the driver's web page the indi version kept as INDI_VERSION it should be 1.8.7 right?

**Comment by knro** [comment]
Thanks, I've corrected this to 1.8.8 which is the next INDI release.

**Pull request merged**
