### PR TITLE
Apply gamma when downscaling 16bit to 8bit stream

### PR DESCRIPTION
**Pull request by nadvornik**
First attempt to solve #982

### CODE REVIEW

**Comment by knro** [comment]
How does it work with the ZWO camera now? can you post pre and post screenshots? 

Under simulators, it seems to apply a high-pass filter and all the lower intensities stars are cut off.

@ebertin is this expected?

post_gamma
pre_gamma

**Comment by nadvornik** [comment]
Near zero it depends on the parameter a = 12.92
With downscaling it is
output = input / 65536 * 256 * 12.92
So it cuts off the lowest ~4 bits of 16bit.
With 12bit ADC it does exactly what I want.

**Comment by knro** [comment]
What about 10 and 14 bits? we have to accommodate these as well.

**Comment by nadvornik** [comment]
I can see these options:
-  use non-standard gamma curve parameters, maybe make it it configurable via property,
- leave it as it is - 10bits is OK and for 14bits there will be 2bits loss of precision - I don't think it would have significant effect - the simulator images above have unrealistic S/N ratio, IMHO.
- implement 16bit streaming

**Comment by ebertin** [comment]
Well the sky background is not supposed to lie at 0 anyway. There should normally be an offset. Unless the images are dark-subtracted, but without applying an offset it would not make any sense because negative noise peaks would be clipped?

**Comment by knro** [comment]
Ok, since this is for streaming, let us check the user feedkback.

**Pull request merged**
