### PR TITLE
Implementation of high-level timers

### PR DESCRIPTION
**Pull request by pawel-soja**
Hi!

I am rewriting camera drivers, I notice quite a lot of redundant code.
This pull request includes a simple implementation of high-level timers like Qt-Timers.
INDI::Timer uses the low level timers from eventloop.c.

Public header files have a description.

### CODE REVIEW

**Comment by knro** [comment]
This simplifies timers so much! Thank you! Is this in any way co-dependent with #1385 ?

**Comment by pawel-soja** [comment]
Changes from #1385  have no effect on this pull request - They are independent. That's why I put in a separate PR.

**Comment by escribana** [comment]
Hi Pawel
I managed to update my rolloff driver (for Siemens LOGO) with 'indielapsedtimer'. Following I tried to use 'inditimer" because or the singleshot option. But I'm getting a compiler warning saying
```
rollogo.cpp:156:43: error: reference to type 'const std::function<void ()>' could not bind to an rvalue of type 'void'
inditimer.h:85:67: note: passing argument to parameter 'callback' here
```
I'm using the following function call
`MotionTimer.singleShot(TimeFrame, checkRoofStatus());`
where 'checkRoofStatus()' returns void.

**Comment by pawel-soja** [comment]
Examples:

**1. Call funcion once**
```cpp
#include <inditimer.h>

class Example
{
public:
    Example();
};

static void someFunction()
{
    // Hello!
}

Example::Example()
{
    INDI::Timer::singleShot(100, &someFunction);
}
```
**2. Call member function once**
```cpp
#include <inditimer.h>

class Example
{
public:
    Example();
    void someFunction();
};

Example::Example()
{
    INDI::Timer::singleShot(100, std::bind(&Example::someFunction, this));
}

void Example::someFunction()
{
    // Hello!
    printf("Hello!\n");
}
```

**3. Call lambda function once**
```cpp
#include <inditimer.h>

class Example
{
public:
    Example();
};

Example::Example()
{
    INDI::Timer::singleShot(100, [this]
    {
        // Hello!
    });
}
```

**4. Create instance of timer**
```cpp
#include <inditimer.h>

class Example
{
public:
    Example();
    void start();

private:
    INDI::Timer someTimer;
};

Example::Example()
{
    someTimer.callOnTimeout([this]
    {
        // Hello!
    });

    someTimer.setInterval(100);
    someTimer.setSingleShot(true); 
}

void Example::start()
{
    someTimer.start();
}
```

**5. Periodic timer**
```cpp
#include <inditimer.h>

class Example
{
public:
    Example();
    void start();
    void stop();

    void callback();

private:
    INDI::Timer someTimer;
};

Example::Example()
{
    someTimer.callOnTimeout(std::bind(&Example::callback, this));
    someTimer.setInterval(500);
}

void Example::callback()
{
    // Hello!
}

void Example::start()
{
    someTimer.start();
}

void Example::stop()
{
    someTimer.stop();
}
```

@escribana You must pass the address to the function, not call it. When using the static function (singleShot) you don't need to create an object.

**Comment by escribana** [comment]
Many thanks for the detailed and illuminating answer!
Indeed I tried the address operator  (1. Call function once) also before, but forgot to omit the parenthesis! (I'm not a "native" C++-programmer.) Searching the web didn't reveal a decent documentation regarding these special calls by address, so I'm really grateful for your tips.
Your knowlegde and experience in C/C++ is of big value for the community and for the INDILIB-project.

**Pull request merged**
