### PR TITLE
Starbook 0.4

### PR DESCRIPTION
**Pull request by not7cd**
* Improved stability
* Ability to activate Starbook using INDI client
* Fix config saving for connection

I still need to update documentation. And I want to update changelog for debian package, but I need guidance. This driver will soon achieve 1.0 version.

### CODE REVIEW

**Comment by knro** [comment]
Great. What help do you need for the Debian packaging?

**Comment by not7cd** [comment]
Version. What I need to distribute this package with version 0.4. Only new entry in `debian/indi-starbook/changelog`?

**Comment by knro** [comment]
Yup, that's pretty much it!

**Comment by knro** [comment]
Let me know if this PR is ready to land

**Comment by not7cd** [comment]
Good to go

**Pull request merged**
