### PR TITLE
Fixing Location issue with Rainbow RST-135

### PR DESCRIPTION
**Pull request by jscheidtmann**
See discussion at https://indilib.org/forum/ekos/9645-rst-135-location-issue.html#71411

### CODE REVIEW

**Comment by knro** [comment]
Thanks! Was this tested as well in other mounts to verify no regressions? I'll test locally as well.

**Comment by jimmy-ck** [comment]
Jasem, no tests so far on any mounts! Be careful.

**Comment by jimmy-ck** [comment]
Built and tested on RPi4 with RST-135 mount: Location pull from mount seems to work now, but there is another fault I think. Obviously KStars/Ekos writes back into the mount after connection process and overrides location information into the EEPROM of the mount, although KStars/INDI is set to "Mount updates KStars". Seems like updateLocation() is called somewhere after starting Ekos. Simply disconnecting and connecting devices in Ekos does not override location in mount, but a restart of INDI Profile and reconnecting does.
Or is this a correct behaviour which I am misunderstanding?

**Comment by jscheidtmann** [comment]
@jimmy-ck This behaviour re upadteLocation() is a different problem and will not be addressed by this pull-request. I suggest you open an issue. I am closing this pull request, as it seems there's still a problem with reading time from the mount.

**Pull request closed without merging**
