### PR TITLE
Driver for OpenAstroTech mounts

### PR DESCRIPTION
**Pull request by anjok**
Adds a driver for [OpenAstroTech](https://openastrotech.com) mounts.

### CODE REVIEW

**Comment by jayjar291** [comment]
This would be nice to have

**Comment by anjok** [comment]
crap. what are the build flags you're using for the pipeplines?

**Comment by knro** [comment]
Thank you! Very interesting projects fits perfectly with INDI Open source :)

Please check and fix the build issues.

**Comment by anjok** [comment]
I'd love to, but I don't get any errors. How do I add "-Werror=format-security" to the build flags?

**Comment by anjok** [comment]
@knro how do i add  "-Werror,-Winconsistent-missing-override" to the build flags? or just try again and see if that fixes the mac build

**Comment by knro** [comment]
We can't modify those, the reported issues should be fixed, like it is done for other drivers in the repo.

**Comment by knro** [comment]
All checks passed. Can you please prepare some documentation for the driver like existing driver in INDI website? e.g. https://indilib.org/telescopes/astrotrac-360.html

**Comment by anjok** [comment]
Sure. How can I upload that? And will you merge before or after?

**Comment by anjok** [comment]
BTW, it's a straight subclass of https://indilib.org/telescopes/meade/lx200-gps.html with a few added features like polar alignment and better focusing. Since that page also just says "it's like astrostar except for..." this is what I'll do too.

**Comment by anjok** [comment]
> We can't modify those, the reported issues should be fixed, like it is done for other drivers in the repo.

My c++ skills aren't really fluent, I was just working on a hunch when fixing those warnings...

**Comment by knro** [comment]
You can upload here (zip the images) and provide explanation in a text file. Once uploaded, I can format it for the website, we just need the content and any special settings a user should know about this driver...etc.

**Comment by anjok** [comment]
No images for the moment. And I'd rather add a link to their <a href="https://wiki.openastrotech.com/en/Knowledge/Software">wiki</a>, as this is where most people will look and I don't want to work in two places.

**Pull request merged**
