### PR TITLE
USB_Dewpoint driver

### PR DESCRIPTION
**Pull request by jpaana**
This pull request adds driver for USB_Dewpoint (http://www.usb-foc.us/) dew controller to change settings and monitor temperatures. It's originally very loosely based on the USB_Focus_V3 driver, but all functionality is obviously different. Communication protocol is fairly similar as well and was quite easy to reverse engineer from the Windows driver debug log, which nicely prints all the commands and responses to the device. No dependencies to any external libraries or anything, just basic serial port communication.

### CODE REVIEW

**Comment by knro** [comment]
Thank you for your contribution! Since this driver is weather related, it needs to be based on the INDI::Weather class. Just yesterday I added MBox Meteostation driver (https://github.com/indilib/indi/blob/master/libindi/drivers/weather/mbox.cpp) you can base your driver on it and modify it as necessary. I hope it's not too much work!

**Comment by jpaana** [comment]
Sure no problem, I wasn't sure if it was weather related enough to warrant using Weather class as it's a fairly simple dew heater controller with just a few temperature and humidity sensors so I made it just aux device instead. I'll update the pull request when ready.

**Comment by knro** [comment]
Oh stop! a dew heater! Nevermind then it does not qualify as a weather device! It's just auxiliary. I should've checked the product first sorry.

**Comment by jpaana** [comment]
Oops, did the change already, it did actually clean up things a bit, but I can revert it as well, yes/no?

**Comment by knro** [comment]
Okay, since it has temperature and humidity sensors, It can be technically used as a weather-reporting device. I guess we can add it twice, once in weather and once in auxiliary (with two different labels perhaps).

**Comment by jpaana** [comment]
Would a suitable compromise be that I move it back to auxiliary directory, but keep the usage of INDI::Weather for the weather related parts? There are temperature sensors in almost all focusers too but I wouldn't look for them in the weather section :)

**Comment by knro** [comment]
I think that would create more confusion. Just revert it back to a generic auxiliary device and call it a day.

**Comment by jpaana** [comment]
Ok, done :)

**Comment by knro** [comment]
Can we get some documentation and screenshots for this driver so I can an add an entry to INDI devices page?

**Comment by jpaana** [comment]
Something like this http://s2.org/~jpaana/usb_dewpoint/?

**Comment by knro** [comment]
That's prefect! One question though: regarding the udev rule, is it specific to USB_dewpoint or that's some FTDI vendor id?

**Comment by jpaana** [comment]
Not FTDI but Primax, but yeah, probably similar generic USB-to-serial-chip:
Bus 001 Device 004: ID 0461:9e41 Primax Electronics, Ltd 

I also have USB_FocusV3 focuser, which also uses different Primax chip:
Bus 001 Device 009: ID 0461:0033 Primax Electronics, Ltd 

so I don't know if the rule is specific enough, but haven't had conflicts myself, with FTDI I've had to use serial numbers to distinguish between devices...

**Comment by knro** [comment]
Thanks, I added the documentation here: http://indilib.org/devices/auxiliary/usb-dew-point.html

**Comment by jpaana** [comment]
Didn't look carefully enough at lsusb output before but it's actually possible to make device specific udev-rules for these:

SUBSYSTEM=="tty", ATTRS{product}=="USB_Dewpoint", SYMLINK+="usb_dewpoint", ENV{ID_MM_DEVICE_IGNORE}="1"

Similar rule for USB_Focus would be:
SUBSYSTEM=="tty", ATTRS{product}=="USB_Focus", SYMLINK+="focuser", ENV{ID_MM_DEVICE_IGNORE}="1"

**Pull request merged**
