### PR TITLE
Shelyak spectrograph

### PR DESCRIPTION
**Pull request by eco747**
We would like to add a new type of driver: spectrograph.
Then Shelyak driver

### CODE REVIEW

**Comment by knro** [comment]
Thank you! INDI already includes a [JSON parser](https://github.com/indilib/indi/blob/master/libs/json.h), so no need to add an additional JSON parser here.

**Comment by eco747** [comment]
ok, but is my merge will be accepted ?
i will change that after merge.

**Comment by knro** [comment]
but why? you can remove json.* now and rebuild the driver against INDI library's json. No need to include files to be deleted later.

**Comment by knro** [comment]
btw, you can make any number of changes to the PR. You don't need to make a new PR.

**Comment by eco747** [comment]
done :)
i remove all old custom json & used indi json lib.

**Comment by knro** [comment]
@ecochard I just pushed some changes to the driver to make it complaint with INDI standards. Please check it out and re-test as I made substantial changes that might have broke the driver.

**Pull request merged**
