### PR TITLE
Deep Sky Dad Field Rotator 1 indi driver

### PR DESCRIPTION
**Pull request by DeepSkyDad**

### CODE REVIEW

**Comment by knro** [comment]
Thanks! Please check the CI errors.

**Comment by DeepSkyDad** [comment]
Is this ok?

**Comment by knro** [comment]
Looks like there is on more error about the index under MacOS.

**Comment by DeepSkyDad** [comment]
Fixed!

**Comment by knro** [comment]
Great! merged! Do you think you can perhaps prepare some documentation for INDI website devices portal?

**Comment by DeepSkyDad** [comment]
Thanks! I will send you an email.

**Pull request merged**
