### PR TITLE
Add driver for myDCP4ESP32 Dew Contoller

### PR DESCRIPTION
**Pull request by hcomet**
The myDCP4ESP32 Dew Controller is a DIY dew controller developed by Robert Brown. This is a driver implementation for it based on the MyFocuserPro2, USB_Dewpoint and SQM drivers.

### CODE REVIEW

**Comment by knro** [comment]
Thank you! We also need to add documentation for this in indilib.org website device section.

**Comment by hcomet** [comment]
I tried to submit documentation but I could not submit the HTML. I was also limited to uploading 3 images. Could not add the 4th.

I've attached the HTML file and the 4th image here.
[MyDCP4ESP32.zip](https://github.com/indilib/indi/files/10938359/MyDCP4ESP32.zip)

**Comment by knro** [comment]
Thanks, I've added all the images. Are there any images for the actual final controller? Couldn't find images online.

**Comment by hcomet** [comment]
I've attached a picture of my controller build with the PCB as a background. Hopefully its usable.

I also noticed that I had copyright symbol in the description that is no displaying properly. Looks like I left the semicolon off of it in the HTML. There's a "&copy Robert Brown" that should be "&copy; Robert Brown". It displayed proper when loading locally in a browser but doesn't display properly on the website. If possible could you update it?

Thanks.
myDCP4ESP32_controller

**Pull request merged**
