### PR TITLE
Feature/xisf as plugin

### PR DESCRIPTION
**Pull request by nouspiro**

### CODE REVIEW

**Comment by knro** [comment]
Can you please check #1848? I think there is a regression there.

**Comment by nouspiro** [comment]
Yes it was. Now it should behave better that it doesn't stop at first bad value but will continue to write other values.

**Comment by knro** [comment]
Can you please check the debian packaging error?

**Comment by nouspiro** [comment]
Wrapper lib doesn't get build because it can't find LibXISF. Most likely github build doesn't have it? It created build package when I was doing it locally with debuild.

```
dh_install: warning: Cannot find (any matches for) "usr/lib/*/libindixisf.so.*" (tried in ., debian/tmp)

dh_install: warning: libindi-xisf missing files: usr/lib/*/libindixisf.so.*
dh_install: error: missing files, aborting
```

**Comment by knro** [comment]
@pawel-soja Do we need to update the packaging workflow to include libxisf? It's built now in the Ubuntu PPA.

**Comment by pawel-soja** [comment]
I'm analyzing the case now. I probably need to add packages to dockerfiles.

**Comment by pawel-soja** [comment]
I see I missed something :) Is the "libxisf" library available as a package for debian/ubuntu etc? Should I prepare an additional build for docker from sources https://gitea.nouspiro.space/nou/libXISF ?

**Comment by nouspiro** [comment]
Not yet. I want to package it for debian but that will probably take quite some time. BTW I am currently rewriting libxisf so it doesn't require Qt.

**Comment by knro** [comment]
It is actually already included in the [stable](https://code.launchpad.net/~mutlaqja/+recipe/libxisf-stable) and [nightly](https://code.launchpad.net/~mutlaqja/+recipe/libxisf-daily) PPAs.

**Pull request merged**
