### PR TITLE
Adding new NexDome Beaver INDI driver

### PR DESCRIPTION
**Pull request by sifank**
Initial release of the INDI driver for NexDome's new Beaver controller made by Lunatico.
Added nexdome_beaver.cpp, nexdome_beaver.h and updated CMakeLists.txt and drivers.xml

Not performed was removing the beaver.ccp, beaver.h skeletons from the 3rdparty repo (and also removing them from the CMakeLists.txt and xml files there).

A README.md for the Nexdome_Beaver driver has been email to Jasem.  Should I put that someplace?

### CODE REVIEW

**Comment by knro** [comment]
@sifank Thank you! Can you please check the error? Regarding the README, I'll add it to the INDI website. Can you attach a zipped file containing screenshots for each tab (in jpg)?

**Comment by sifank** [comment]
Changed .setText args to strings, added override to SetCurrentPark and SetDefaultPark and fixed an issue I found with shutter open on unpark policy.

[beaver-images.zip](https://github.com/indilib/indi/files/7965100/beaver-images.zip)

**Comment by sifank** [comment]
(Just replied to a diff email to you) I've fixed the issues and submitted
another PR.  I attached a zip file of the jpg images to that.

Also, are you going to remove the beaver skeleton files from the Lunatico
3rdparty drivers or is that something I should do as well, then submit a PR
for that?

Sifan
Carpe Nocturnum ...

**Comment by knro** [comment]
Yes I will remove from 3rd party

**Comment by knro** [comment]
Looks like the zip file is corrupted?

**Comment by sifank** [comment]
Can I send a tar?

Sifan
Carpe Nocturnum ...

**Comment by sifank** [comment]
Here's a tar file of the images.

Sifan
Carpe Nocturnum ...

**Comment by knro** [comment]
I can't find anything attached on Github or email.

**Comment by sifank** [comment]
Hi Jasem, I attached 'BeaverImages.tar' to this email.  Let me know if
you received it.

Sifan
Carpe Nocturnum ...

**Comment by knro** [comment]
I think you need to directly attach in the Github interface itself. or upload to dropbox and share a link for example. Sorry I don't know why this isn't working.

**Comment by sifank** [comment]
Jasem, here's a link to Google drivers where I placed the images.  See if
this works:

https://drive.google.com/drive/folders/10MKjXc7uDVbiS8_lrL9VlQ-mCpYxQYjW?usp=sharing


Sifan
Carpe Nocturnum ...

**Pull request merged**
