### PR TITLE
Detect another Celestron Nexstar EVO broadcast

### PR DESCRIPTION
**Pull request by luzik**
My brand new EVO sends such packets in AP mode

IP 192.168.123.102.4097 > 255.255.255.255.55555: UDP, length 108

..but listen on TCP 2000

### CODE REVIEW

**Comment by knro** [comment]
@jochym Can you please check?

**Comment by luzik** [comment]
Uhg, this source UDP port is quite dynamic. Today it was 4098. Nevertheless source UDP port should not be in relation with listening TCP port.

**Comment by jochym** [comment]
Yes. You are right. Using source port in the detection is wrong. It may change with theimplementation and system activity.

**Comment by jochym** [comment]
Are you shure @luzik that the package length is different?

**Comment by luzik** [comment]
Positive. First comment actually contains tcpdump line. Beside that "recvlen" printf was tested.

**Pull request closed without merging**
