### PR TITLE
Silence a warning for gcc-7

### PR DESCRIPTION
**Pull request by kecsap**

### CODE REVIEW

**Comment by TallFurryMan** [comment]
Now we're getting bleeding edge. I note that some drivers are set to Off. Do you plan to raise issues for them

**Comment by TallFurryMan** [comment]
and let authors fix?

**Comment by kecsap** [comment]
@TallFurryMan Which drivers do you mean?

**Comment by TallFurryMan** [comment]
There are two options in libindi and three in 3rdparty. I can manage the build for the MGen driver with gcc 4, 5, 6 and 7 (though I don't know if my system will be able to slot all these simultaneously), but do we consider others deprecated?

**Comment by kecsap** [comment]
@TallFurryMan: I think Jasem mentioned that the disabled drivers have no maintainer and we can't test it. On the other hand, if we enable any of these unstable drivers, Travis CI already build all gcc versions+clang 4.0 with warnings turned to errors now.

**Comment by TallFurryMan** [comment]
Understood. How can I trigger a Travis build? Should I open a PR with for instance the MGen enabled, and fix repeatedly afterwards? Or is there another way?

**Comment by kecsap** [comment]
@TallFurryMan: Exactly. Otherwise, you have to manage your local builds of gcc, clang yourself.

**Comment by TallFurryMan** [comment]
About Travis, I observe the distribution is Ubuntu trusty. This causes a dependency for the MGen driver (libftdi1-dev) not to be readily available (libftdi1 is though). Do I import the source and build the dev resources or do we move to a later distribution for the worker? (isn't it 16.04 which is officially supported by indi?)

**Comment by knro** [comment]
Travis doesn't support 16.04 thus far unfortunately. It's odd but that's their policy.

**Comment by TallFurryMan** [comment]
I'll try to add the ppa for libftdi1 to the Travis config. Fairly new to this tool, sorry :)

**Pull request merged**
