### PR TITLE
Adding CFITSIO to cmakelists for indi XISF and changing linking step …

### PR DESCRIPTION
**Pull request by rlancaste**
…to make it work better on MacOS

### CODE REVIEW

**Comment by knro** [comment]
Apparently this caused MinGW to fail?

**Comment by rlancaste** [comment]
The following REQUIRED packages have not been found:
[77](https://github.com/indilib/indi/actions/runs/4287243289/jobs/7467868579#step:4:78)

[78](https://github.com/indilib/indi/actions/runs/4287243289/jobs/7467868579#step:4:79)
 * CFITSIO, A library for reading and writing data files in FITS (Flexible Image Transport System) data format, <http://heasarc.gsfc.nasa.gov/fitsio/fitsio.html>
[79](https://github.com/indilib/indi/actions/runs/4287243289/jobs/7467868579#step:4:80)
   Provides INDI with FITS I/O support.
[80](https://github.com/indilib/indi/actions/runs/4287243289/jobs/7467868579#step:4:81)

[81](https://github.com/indilib/indi/actions/runs/4287243289/jobs/7467868579#step:4:82)

**Comment by rlancaste** [comment]
find_package(CFITSIO REQUIRED)
 
Maybe it should not be required?

**Comment by rlancaste** [comment]
I am not sure why this would still come up as being CFITSIO required when I removed the requirement

**Comment by knro** [comment]
@pawel-soja Any ideas what's causing the MinGW failure? Also Debian packages have been failing for quite a while now after adding libxisf. I updated the dependencies, but it had no effect. The docker containers needs to be updated?

**Comment by pawel-soja** [comment]
I'll check it.

**Comment by pawel-soja** [comment]
https://github.com/indilib/indi/blob/754d269598067861a36ff41bd66f3b9934757518/CMakeLists.txt#L145

FeatureSummary has a `TYPE REQUIRED` for this package. So if there is a reference to `find_package(CFITSIO)` somewhere, it will require the package.

If `CFITSIO` is to be optional, I suggest changing `TYPE REQUIRED` to `TYPE OPTIONAL`

**Comment by knro** [comment]
This is no longer required after removing Qt5 dependency

**Pull request closed without merging**
