### PR TITLE
Ap park3

### PR DESCRIPTION
**Pull request by wildi**
Hello Jasem
AP mount does a normal meridian flip after a :CMR sync being at HA > 0 and the mount is in state "West of the Pier". :CMR is reenabled.  I set default to :CM since AP says not to use it during init phase.
I synced this fork with indi_cor yesterday.

Kind regards, bye, wildi

### CODE REVIEW

**Comment by knro** [comment]
@wildi Thank you! Did Mike test this?

**Comment by wildi** [comment]
You are welcome, yes, Mike tested it in the southern and I in the northern hemisphere (mode: simulation). As soon as I have access to my observatory, I'll do the same for GTOCP2 controller.

**Comment by knro** [comment]
@wildi Alright, I'll await your final confirmation before merging this.

**Comment by wildi** [comment]
Hello Jasem
yes please, go ahaed, kind regards, wildi

**Pull request merged**
