### PR TITLE
Refactoring - Typed property

### PR DESCRIPTION
**Pull request by pawel-soja**
Hi!

As previously mentioned (#1361), I am moving to stage two.

My plan:
1. Implementation of PropertyView/WidgetView decorators (collection of used low-level functions)
2. **implementation of widgets (eg PropertyText...) which have methods from PropertyView/WidgetView and additionally inherit from INDI::Property.**
3. implementation of signals / slots for PropertyText...

In brief:
- minor PropertyView / WidgetView fixes
- For example, Merge ISwitch** and ISwitchVectorProperty** to PropertySwitch, see defaultdevice_p.h
- Ability to dynamically change the number of elements, see "ConnectionModeSP"

 ** ISwitch and ISwitchVectorProperty is the same as WidgetView <ISwitch> PropertyView <ISwitch> with additional method implementation.

I'm going to spend this night on additional testing. If there is anyone willing, I invite you to test ;)

### CODE REVIEW

**Comment by knro** [comment]
Thanks! This is a huge change so let's try to test all aspects. The ability to change number of elements is awesome! The tutorials drivers need to be updated soon as well to reflect these changes.

**Comment by pawel-soja** [comment]
Thanks for the merge. I did not find any bugs. I will replace old "widgets" and additionally test new "widgets".

I will correct the examples in the "examples" directory.
For documentation, should I submit PR to https://github.com/indilib/docs ?
Anything else?

**Comment by knro** [comment]
I tested it for a couple of hours today and didn't see any bugs from the client perspective. Still we might encounter some so we have to keep testing. Right, please submit PR to docs repo to update the documentation, it's still using the old system.

**Comment by pawel-soja** [comment]
I also check how to get rid of it:
```cpp


void ISGetProperties(const char *dev)
{
    mydriver->ISGetProperties(dev);
}

void ISNewSwitch(const char *dev, const char *name, ISState *states, char *names[], int n)
{
    mydriver->ISNewSwitch(dev, name, states, names, n);
}

void ISNewText(const char *dev, const char *name, char *texts[], char *names[], int n)
{
    mydriver->ISNewText(dev, name, texts, names, n);
}

void ISNewNumber(const char *dev, const char *name, double values[], char *names[], int n)
{
    mydriver->ISNewNumber(dev, name, values, names, n);
}

void ISNewBLOB(const char *dev, const char *name, int sizes[], int blobsizes[], char *blobs[],
               char *formats[], char *names[], int n)
{
    mydriver->ISNewBLOB(dev, name, sizes, blobsizes, blobs, formats, names, n);
}

void ISSnoopDevice(XMLEle *root)
{
    mydriver->ISSnoopDevice(root);
}

```
And I will take care of the documentation - so as not to modify it every now and then.
The old "widget" method works, so there should be no problems, at best there will be more to refactor.

**Pull request merged**
