### PR TITLE
Fix sockets in INDI::BaseClient

### PR DESCRIPTION
**Pull request by pawel-soja**
@knro can you check?

### CODE REVIEW

**Comment by knro** [comment]
Great, tested and looks quite stable. Will test it more with Windows as well. Thanks!!

**Comment by knro** [comment]
On Raspberry pi, it's still not completely stable and I get SIGPIPEs sometimes when trying to connect/disconnect a few times in a row, or connect to INDI Web Manager server, kill that, then run Simulator Profile back and forth.

Let me check on Windows as well.

**Comment by pawel-soja** [comment]
I also tested between a PC and a Raspberry. Can you add the backtrace again?

I will review the code carefully this evening.

**Comment by knro** [comment]
```
C:\CraftRoot\build\_\6be5d956\indiclient\libs\indibase\indiutility.h(37): error C2061: syntax error: identifier 'mode_t'C:\CraftRoot\build\_\6be5d956\indiclient\libs\indibase\property\indipropertyview.h(276): error C3861: 'strndup': identifier not found
C:\CraftRoot\build\_\6be5d956\indiclient\libs\indibase\property\indipropertyview.h(694): warning C4267: 
```

There is also build error on Windows, even though I recall this was fixed before!

**Comment by pawel-soja** [comment]
strndup https://github.com/indilib/indi/pull/1429

**Pull request merged**
