### PR TITLE
Bugfix: update focuser temperature in alluna tcs2 driver

### PR DESCRIPTION
**Pull request by peter-englmaier**
I noticed, that the focuser temperature was not updated in kstars and other clients. The reason was, that the  .apply() method was not called when reading new values from the device.

Other (minor) changes:
- update temperature more often (every 10 seconds instead of once every 5 minutes)
- update fan speed less frequently (very 30 seconds instead of every 3 seconds)
- corrected the copyright message in the header file to reflect my authorship (getting it in sync with the source file).

### CODE REVIEW

**Comment by knro** [comment]
Thank you @peter-englmaier can you please check the MacOS errors?

**Comment by peter-englmaier** [comment]
@knro: This seems to be quite deeply rooted in indi. I have not touched any code near that. 

It seems, on a mac, the 1-bit wide field 'ok' is interpreted as a signed integer. So instead of `sp->ok = 1`  one needs to set  `sp->ok = -1`, however I rather would change the type to unsigned. With this the error is gone, but instead it fails for some other reason. Perhaps something has changed with the macos compiler defaults?

**Comment by peter-englmaier** [comment]
@knro I do not grasp why the MacOS build fails. The compiler complains about missing function prototypes, but those are clearly present at the beginning  of the source code:
```
static int compile(int prec);
static int execute(double *result);
static int parse_fieldname(char name[], int len);
```
Can you please help?

**Comment by knro** [comment]
Yes sorry, hopefully the issue is now fixed. I'm running the builds again.

**Comment by peter-englmaier** [comment]
@knro Ok, I see you have committed some changes. I try to rebase and see if it compiles again.

**Comment by peter-englmaier** [comment]
Looks like my merge has messed things up, I should probably start from scratch...

**Comment by peter-englmaier** [comment]
I hope #2055 is going to compile... it is rebased on the latest master

**Comment by peter-englmaier** [comment]
This PR is replaced by #2055, so I am closing it.

**Pull request closed without merging**
