### PR TITLE
Added support for TeenAstro focuser 

### PR DESCRIPTION
**Pull request by mlnoga**
This pull request adds support for the TeenAstro focuser. It supports all currently available INDI focuser capabilities except FOCUSER_HAS_BACKLASH, which is not yet implemented in the TeenAstro focuser device firmware. It also supports all commands supported by the serial protocol of the TeenAstro focuser firmware, except named goto locations as INDI already provides those in the driver.

All controls relating to basic location can be found on the Main Controls tab. The remaining controls can be found on the Focuser tab and include motor settings for direction/steps/microsteps/resolution/current, motion settings for speeds/accelerations, as well as device firmware reboot and EEPROM erase.

Confirmed to work on my RasPi4 and TeenAstro focuser, as well as François Desvallées machine.

### CODE REVIEW

**Comment by knro** [comment]
Thank you! Can we get some documentation submitted for INDI devices page?

**Comment by mlnoga** [comment]
Happy to take screenshots of the two settings panels, and to write a page. How do I submit it, though? There seems to be no documentation folder in here. The separate [indilib/docs](https://github.com/indilib/docs) repo has a drivers folder, but seems to contain no documentation on drivers, only how to create drivers. Please advise.

**Comment by knro** [comment]
There is documentation here: https://github.com/indilib/indi/tree/master/drivers

You can also sign up for indilib.org and then [submit an entry](https://indilib.org/individuals/devices/add.html). I think you can attach the screenshots here in a zip file and I'll upload them.

**Comment by mlnoga** [comment]
Here come the screenshots: 
[teenastro_focuser_screenshots.zip](https://github.com/indilib/indi/files/6218212/teenastro_focuser_screenshots.zip)

**Comment by knro** [comment]
Thanks! Can you submit the entry in indilib?

**Pull request merged**
