### PR TITLE
Add correctness attributes

### PR DESCRIPTION
**Pull request by spacekitteh**
These attributes will hopefully encourage proper defensive programming by, for example, warning when an error code is returned but not checked.

### CODE REVIEW

**Comment by knro** [comment]
Thanks! Great idea! Would a gnu keyword work on MacOS?

**Comment by spacekitteh** [comment]
Yep, Clang v6 recognises a bunch of gnu attributes: https://releases.llvm.org/6.0.1/tools/clang/docs/AttributeReference.html

**Comment by spacekitteh** [comment]
All the supported compilers (I think all of them) implement the "ignore unrecognised attributes" part of the C++17 spec, so as many as desired can be added.

How do you want to go about doing this? I haven't got any real familiarity with the indi library internals, so I don't know how to correctly handle various return values; and the CI has -Werror enabled for it it seems.

**Comment by knro** [comment]
Thanks, yes we treat all warnings as errors to ensure code quality. Can you check the areas where these calls are failing and perhaps patch them up?

**Comment by spacekitteh** [comment]
That's what I mean - I probably wouldn't know how to patch them up.

**Comment by knro** [comment]
Alright, I'll take a look after we release INDI tomorrow.

**Comment by spacekitteh** [comment]
Cool. I'll keep adding more attributes to my branch in the meantime.

**Pull request closed without merging**
