### PR TITLE
Starbook 0.5

### PR DESCRIPTION
**Pull request by not7cd**
This update should cover all RPC commands in the command interface class.
There will be increased usage of exceptions to handle unknown states.

### CODE REVIEW

**Comment by knro** [comment]
Can you please check the CI errors?

**Comment by knro** [comment]
Would this work also with Vixen Starbook Ten?

**Comment by not7cd** [comment]
I'm getting reports that it works to some extent with Starbook TEN. I can't support this, so maybe someone with access to one could contribute.

**Comment by knro** [comment]
Ok great thanks!

**Pull request merged**
