### PR TITLE
Bee Focuser Device Driver

### PR DESCRIPTION
**Pull request by glowmouse**
Indi device driver and unit testing for an Open Source hardware focuser project, (https://github.com/glowmouse/beefocus)

These are mostly new files.  The code can be browsed here:  https://github.com/glowmouse/indi/tree/develop/3rdparty/indi-beefocus

Suggested reading order:

- README.md
- driver/beefocus.*             This is the core driver
- driver/beeconnect*          Connection utilities for the driver
- driver/beesimfirmware*   Interface to firmware for simulation mode (used in testing)
- unit_tests/*                      Unit Testing code + test infrastructure
- firmware/*                        Firmware for programming the ESP8266.  Also used by the simulator

There's code in this driver that may be useful to the general Indi community.  i.e., test infrastructure.

Continuous Integration was passing before I merged in the master branched and rebased my changes.  see,  https://travis-ci.com/glowmouse/indi/builds

### CODE REVIEW

**Comment by knro** [comment]
Beautiful work Andrew! I see a header for WiFi secrets.. could this be made into a config file instead of a header? What's the rational behind a header? Can you also share screesnhot for all the tabs for this focuser as it is needed for the online documentation.

**Comment by glowmouse** [comment]
WIFI Secrets is loaded into the focuser's firmware.  My expectation is that the focuser is connecting to an existing hotspot.  i.e., my setup uses a Raspberry Pi 3 to control the telescope.  The PI creates a hotspot, the focuser connects to the PI's hotspot, and I VNC into the PI from my laptop to control everything.

I'm working on documentation this weekend - I'll make screen shots a priority.

**Comment by glowmouse** [comment]
I've created a basic usage page with screen shots:

https://github.com/glowmouse/beefocus/blob/master/indi_docs/indi_usage_docs.md

**Comment by knro** [comment]
Thanks! Btw, you do not need to override connection mode to add "Simulation". You can already have a simulation switch (like all other drivers) in the option tabs, and when that switch is enabled, then you're in simulation mode.

**Comment by knro** [comment]
Can you send a PR for the debian packaging so we can add it to the official PPA?

**Comment by knro** [comment]
Documentation added here: https://indilib.org/devices/focusers/bee-focuser.html

**Comment by knro** [comment]
Any update on the debian PR so that debian packages are built for end users?

**Comment by glowmouse** [comment]
I started on it tonight.  I've never done a debian package before so there's a bit of learning - I'm starting with the scripts in .circleci.  Luckily I have the week off work.

**Comment by knro** [comment]
You can just copy one of the debian directories and use it as base, like for example debian/indi-eqmod

**Pull request merged**
