### PR TITLE
Convert between Observed (Jnow) and J2000 catalogue places correctly

### PR DESCRIPTION
**Pull request by Chris-Rowland**
The JNow to J2000 conversions in the CCD and Guide simulators were not removing aberration and nutation to get back to the J2000 catalogue position required for the CCD frame generator.
This led to alignment errors of 10 to 40 arc seconds that couldn't be removed by a telescope sync.

This PR adds a LibAstro class which implements static functions to do the conversions between Observed  and Catalogue correctly adding and removing aberration and nutation as required.

CCD Simulator now gives a raw alignment error of about 5 arc seconds.

The JNow to J2000 conversion appears to be done incorrectly in other places and these functions should help there as well, look for ln_get_equ_prec2.

Some updates to the telescope simulator have also happened, principally improving the Abort function to stop everything and adding variable tracking rates.

The Gemini pier side changes have also appeared, I though they had already been PRed.

And (!) the indiccd pier side changes!

Sorry for so many things, not good practice I know.  I thought that several of these had already  been submitted.

### CODE REVIEW

**Comment by knro** [comment]
Thank you! Can you please sync your fork master branch of indi repository first then re-submit the PR?

**Comment by Chris-Rowland** [comment]
Do I need to close this PR before trying again?  I've tried syncing my fork by doing a fetch and a merge.
I don't seem to be able to do a commit because I have nothing different to commit.

**Comment by Chris-Rowland** [comment]
Do you mean close this pull request then check out and merge to my current fork, then add the backed up files, commit and start the PR again?

I tried a check out and merge and my system seems to think there's nothing to commit.
I don't mind, it will give me a chance to do this properly, as three separate PRs.

**Comment by knro** [comment]
yeah please rebase and then submit an updated PR.

**Pull request closed without merging**
