### PR TITLE
Fixing location accuracy and date&time for RST-135

### PR DESCRIPTION
**Pull request by jimmy-ck**
fixed:
- location accuracy is now received in arcsec resolution
- date & time & UTC offset are received properly now
- it should not interfere in any ways with classic LX200 mounts
- I renamed a lot of "title" comments because I found them misleading

not fixed:
- location in mount gets overwritten when Ekos is started from scratch

Ongoing discussion in: https://indilib.org/forum/ekos/9645-rst-135-location-issue.html?start=24#71910

### CODE REVIEW

**Comment by TallFurryMan** [comment]
I think that your computation of the location, by adding sexagesimal components, has a problem when d is negative. But I don't know if that can ever be the case.

**Comment by knro** [comment]
Thanks! I don't think we should be changing lx200driver at all. Can you please just implement them in the rainbow driver? I did yesterday with sendScopeLoction, I believe they can be done for all the others leaving lx200 part unaffected by this change.

**Comment by jimmy-ck** [comment]
@TallFurryMan Thanks for pointing that out. I tested only for positive coordinates – that’s true. Will test this later this das.

@knro Yes, should be possible. Will do this later this day as well.

**Comment by jimmy-ck** [comment]
I'm closing this pull request and opening a new one with changes only in rainbow.cpp.

**Pull request closed without merging**
