### PR TITLE
Get camera temperature from EXIF data when using Canon DSLRs

### PR DESCRIPTION
**Pull request by k-ross**

### CODE REVIEW

**Comment by k-ross** [comment]
Looks like libtiff5-dev isn't installed on the build server.

**Comment by jochym** [comment]
But it seems that there is still other problem on travis. Please investigate it separately.

**Comment by k-ross** [comment]
Looks like an unused parameter warning is being treated as an error. Will fix shortly.

**Comment by jochym** [comment]
OK. Seems to be fixed.

**Comment by k-ross** [comment]
Great!  Now you guys just need to decide if you want this change or not. :)

**Comment by jochym** [comment]
That is a prerogative of our benevolent dictator. @knro what you think ? Looks interesting and fairly non-intrusive and would help with dark libraries for DSLR.

**Comment by knro** [comment]
Great work, this is a long requested feature. Is this limited only to Canon? If yes, then TemperatureNP should only be defined for Canon as well.

**Comment by k-ross** [comment]
Yes only Canon.  I will make that change to define in only for Canon

**Comment by k-ross** [comment]
I made that change.  This change is limited to Canon, but other camera makers also supply the info, in their own proprietary tags.  Needs to be handled separately for each camera maker. Since I only have Canon to test with, this is what I have done.

**Pull request merged**
