### PR TITLE
Deep Sky Dad AF2 driver

### PR DESCRIPTION
**Pull request by DeepSkyDad**

### CODE REVIEW

**Comment by knro** [comment]
Can you please check and correct the CI errors?

**Comment by DeepSkyDad** [comment]
If I understood correctly, the problem is in indentation?

"this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’"

I fixed the wrongly indented if.

**Comment by DeepSkyDad** [comment]
These are remanining errors, I think its not connected to AF2 driver?

**file included from /Users/travis/build/indilib/indi/3rdparty/indi-astromechfoc/astromech_focuser.cpp:22:
/Users/travis/build/indilib/indi/3rdparty/indi-astromechfoc/astromech_focuser.h:32:14: error: 'Disconnect' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
        bool Disconnect();
             ^
/usr/local/include/libindi/defaultdevice.h:443:22: note: overridden virtual function is here
        virtual bool Disconnect();
                     ^
1 error generated.
make[2]: *** [indi-astromechfoc/CMakeFiles/indi_astromechfoc.dir/astromech_focuser.o] Error 1
make[1]: *** [indi-astromechfoc/CMakeFiles/indi_astromechfoc.dir/all] Error 2
make: *** [all] Error 2
The command "travis-ci/build-3rdparty.sh" failed and exited with 2 during .**

**Comment by knro** [comment]
Yeah, it's fine now, thanks!

**Pull request merged**
