### PR TITLE
Refactoring - use INDI::PropertyXXX - Stage 1 - Conflict check

### PR DESCRIPTION
**Pull request by pawel-soja**
Hi!

**DO NOT MERGE.**

Replacement IXXX/IXXXVectorProperty to INDI::PropertyXXX.
Pull request contains most of the source modifications (not all)

**Advantages:**
- Declaration of one class instead of two.
- Dynamic number of elements.
- Safe getters and setters instead of accessing a low-level structure.
- Safe functions for checking - Don't use strcmp/strncmp, use e.g. isNameMatch("SOME_NAME")
- Currently, only items are backward compatible. The INDI::WidgetView<IXXX> template is used, inheriting from IXXX.

**Potential issue:**
Public declarations 'IXXX/IXXXVectorProperty' can be used by other 3rd party classes.
Refactoring is removing the redundant array of "widgets" - and this can cause problems referencing a non-existent variable.

Before:
```cpp
#include "indiapi.h"

/* ... */
public:
    /* ... */
    ITextVectorProperty StatusTP;
    IText StatusT[3] {};
    /* ... */
```
After:
```cpp
#include "indipropertytext.h"

/* ... */
public:
    /* ... */
    INDI::PropertyText StatusTP {3};
    /* ... */
```

I suspect the indi-3rdparty build will fail - but it was successful nevertheless. I need help assessing how big the problems are causing these changes.

Please, test the library with other projects - mainly I mean the compilation process.

Regards,
Paweł Soja

### CODE REVIEW

**Comment by knro** [comment]
Thank you, I need to take a closer look at this change since it is quite a fundamental departure compared to existing driver code. So not only how does it affect existing drivers, but how does it affect clients like Ekos, PHD2 and others?

Also, looks like refactoring existing drivers would take quite a bit of work. Out of tree drivers would fail, perhaps we can create a migration guide for such cases.

**Comment by knro** [comment]
Unrelated to this PR specifically, but indi does not compile on Windows now since it does not have strndup. What's the best way to go about this? define one or use another function completely?

**Comment by pawel-soja** [comment]
If it's not super urgent, I'll have a solution.

What do you think about GitHub Actions?
I can prepare CI for linux / macos / windows.
Additionally, building packages on the master branch for use in building indi-3rdparty - all automatically.

**Comment by knro** [comment]
@pawel-soja That would be AWESOME! We've been waiting for CI in indi-3rdparty for over a year now! I'll grant you the necessary permissions so you can do that. I'm not familiar with Github Actions, need to read on that a bit.

**Comment by pawel-soja** [comment]
What systems do you prefer?
For **linux**, I will make an auxiliary script for installing dependencies.
A bit of fun with that (https://github.com/pawel-soja/github-actions-test/blob/master/scripts/requisites-install.sh).
Currently added
```
container: ["centos:7", "ubuntu:latest", "debian:latest", "fedora:latest"]
```

CentOS 8 doesn't have all the packages, however if you would like this system I will deal with it later.
I also found this problem on the forum:
https://indilib.org/forum/general/7151-centos-install.html

I will create build and install scripts for general use. This will facilitate manual compilation and installation.
For example:
```bash
#!/bin/bash

set -e

SRCS=$(dirname $(realpath $0))/..

mkdir -p build/indi-core
pushd build/indi-core
cmake \
    -DCMAKE_INSTALL_PREFIX=/usr/local \
    -DFIX_WARNINGS=ON \
    -DCMAKE_BUILD_TYPE=$1 \
    -DINDI_BUILD_UNITTESTS=ON \
    . $SRCS

make -j3
popd
```

The script knows where the sources are, and you can run it anywhere. e.g:
```
pawel@debian:/tmp/indi-tmp$ /home/pawel/Projects/indi-actions/scripts/indi-core-build.sh 
....
pawel@debian:/tmp/indi-tmp$ ls
build
```

MacOS and Windows will be in separate workflows.

**Comment by knro** [comment]
Centos isn't critical. I mean opensuse is probably more relevant than it is. However, debian+ubuntu+fedora is all we need really cover most use cases in the wild.

**Comment by pawel-soja** [comment]
Great, opensuse has a broken git package... ;)
And I thought that today I will prepare everything.

**Comment by knro** [comment]
If Ubuntu is working at this stage that would be great, then other distros can be added.

**Comment by pawel-soja** [comment]
OK, pre-launched.
image

What is:
- Image building (ubuntu / debian / fedora)
- Image repository (https://github.com/orgs/indilib/packages)
- Recompiled source packages (https://github.com/indilib/indi/actions/runs/695831034)

In indi-3rdparty I set:
``
-DFIX_WARNINGS = OFF
``
I had fixes somewhere, when I find it I will push it :)

What else will I do:
- Addition of other systems
- Adding missing packages (3rdparty apt)
- Maximum CPU usage when building

After fixing the ZWO, I can prepare more automations, e.g. with releases.
@knro Is **CircleCI** still needed for anything?
Anything else I should add so you can safely **turn off**?

**Comment by knro** [comment]
Thank you! I believe @jochym was involved with CircleCI initially.. please correct me if I'm wrong.

**Comment by pawel-soja** [comment]
Clang must be added to the tests. Fun things on macOS :)
image

**Comment by pawel-soja** [comment]
Cześć @jochym !
I will support the work of GitHub Actions. Can I disable building on CircleCI?

@knro In the future I'd like to have a look at how repository packages (debian / ubuntu) are made. I can unify everything on GitHub.

**Comment by pawel-soja** [comment]
Hi @knro 

I think I've already asked, but I lost this thread.
Would you give me tips on how you install a library on Windows?
Maybe you have a description somewhere?

Windows is not my strength, but I will try to do something :)

We already have MacOS.
image

**Comment by knro** [comment]
INDI client component compiles on Windows only, but not the drivers. The drivers are developed for Linux, with a few that have native MacOS support as well.

**Comment by pawel-soja** [comment]
So I understand that only INDI_BUILD_CLIENT should be enabled?
I see the zlib library is required.
Do you have information on how to compile on Windows or should I reinvent the wheel?

**Comment by knro** [comment]
Closing the PR since it is out of date.

**Pull request closed without merging**
