### PR TITLE
Add libindiclient shared library

### PR DESCRIPTION
**Pull request by pawel-soja**
Solving the problem of building a deb package.

### CODE REVIEW

**Comment by pawel-soja** [comment]
`indiclient.so` never built before, when I added options to build static and shared libraries, by default the shared library is additionally built. From what I can see, other libraries in `INDI Core` want to link it instead of static.

**Comment by pawel-soja** [comment]
Ahhh fail. I will add package build testing to CI later.

**Comment by knro** [comment]
indiclient library now fails to build on KDE Craft build system due to missing zlib.h

I added ZLIB_INCLUDE_DIR to a couple of places, but it still fails to find the file. CMake reports that zlib was found in the system, so that was not an issue.

```
D:\CraftRoot\build\_\dec7706e\indiclient\libs\indicore\indililxml.h(488): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
[32mD:\CraftRoot\dev-utils\bin\ninja.exe: b"D:\\CraftRoot\\build\\_\\dec7706e\\indiclient\\libs\\indicore\\indililxml.h(488): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data"[0m
D:\CraftRoot\build\_\dec7706e\indiclient\libs\indidevice\basedevice.cpp(42): fatal error C1083: Cannot open include file: 'zlib.h': No such file or directory
[32mD:\CraftRoot\dev-utils\bin\ninja.exe: 
```
Any ideas?

**Comment by pawel-soja** [comment]
I think I know what it is. Give me 1 hour and I'll be at the computer and upload the fix.

**Comment by pawel-soja** [comment]
You were on the right track! `indidevice` compiles as an object library and required the `zlib.h` header to compile as shown by the error. To compile objects, linking of libraries is not required, but access to headers is required.

Following your lead, I put a similar commit on master.

Let me know if anything else comes up.

**Pull request merged**
