### PR TITLE
TeenAstro INDI device driver

### PR DESCRIPTION
**Pull request by fdesvallees**
**What is TeenAstro**
It is an open source telescope mount controller derived from OnStep, with a user interface based on the FS2 system by Astro-electronic (Michael Koch). It is fully documented at https://groups.io/g/TeenAstro/wiki/home

**Driver design** 
The TeenAstro INDI driver derives directly from the simplest driver with basic functionality (lx200basic), and adds the TeenAstro specific functions. When available, the existing LX200 functionality is used, if not it is copied from OnStep and other drivers.

Source files : lx200_TeenAstro.cpp, lx200_TeenAstro.h
Driver info: indi_lx200_TeenAstro

**Connection options**
INDI / Ekos runs either on a PC, Mac or on a Raspberry Pi. The connection between this device and TeenAstro is done either through USB (the Telescope port on the main unit), or through Wifi to the Smart Hand Controller (SHC), port 9999 (IP address depends on the network). When running through Wifi, the SHC requires a firmware version that allows permanent IP connections. (The standard version as of December 2019 closes connections after 2 seconds and cannot be used).

**Mount Type**
TeenAstro supports German Equatorial, Alt Azimuth, Fork Azimuth and Fork equatorial mounts. However the current driver only supports German Equatorial.
Current features
GOTO: yes 
Sync: yes
Slew Speeds: Guide, ½ x, 1x, 2x, 4x, 16x, 32x 64x, ½ Max, Max (Max speed depends on mount and motors, and is configured through the hand controller)
Track Rates: Sidereal, Solar, Lunar
Tracking can be disabled
Auto Meridian Flip: no
Configurable custom parking positions: yes
Pulse-guiding: yes
Guide Rates: 0.25x, 0.5x, 1x
ST4 Guiding: yes

Sync and Alignment (2 or 3-star) is done using the hand controller. The mount needs to be aligned before connecting the driver. 
Guiding can be done with ST4 or software (pulse-guiding)
4 sites are stored, with their coordinates including altitude (elevation)
An optional GPS device can be connected, its functionality is not exposed to the INDI driver.
[TeenAstro INDI device driver.pdf](https://github.com/indilib/indi/files/4050669/TeenAstro.INDI.device.driver.pdf)

### CODE REVIEW

**Comment by knro** [comment]
Thank you! Regarding the documentation, it needs to follow this template: https://github.com/indilib/indi/tree/master/drivers#mount

So please send one using this template, along with screenshot for each tab.

**Comment by fdesvallees** [comment]
Thanks Jasem. No problem for the screenshots, but do I have to return the HTML form?
  
  
   It would be easier to use markdown format or equivalent.
  
  
   
  
  
   François
  
  
   
  
  
   
    On 15 January 2020 10:43 Jasem Mutlaq <notifications@github.com> wrote:
   
   
    
   
   
    
   
   Thank you! Regarding the documentation, it needs to follow this template: https://github.com/indilib/indi/tree/master/drivers#mount
   So please send one using this template, along with screenshot for each tab.

**Comment by fdesvallees** [comment]
Hi Jasem:
  
  
   
  
  
   I updated the comment with the template and screenshots. Hope this is okay, let me know.
  
  
   
  
  
   Thanks!
  
  
   François
  
  
   
  
  
   
    On 15 January 2020 10:43 Jasem Mutlaq <notifications@github.com> wrote:
   
   
    
   
   
    
   
   Thank you! Regarding the documentation, it needs to follow this template: https://github.com/indilib/indi/tree/master/drivers#mount
   So please send one using this template, along with screenshot for each tab.

**Comment by fdesvallees** [comment]
Thank you Jasem!
  
  
   
    On 16 January 2020 11:12 Jasem Mutlaq <notifications@github.com> wrote:
   
   
    
   
   
    
   
   Merged #1065 into master.

**Pull request merged**
