### PR TITLE
feat(): Adding wanderer cover v3

### PR DESCRIPTION
**Pull request by grm**

### CODE REVIEW

**Comment by grm** [comment]
Through github ? or indi website ?

**Comment by grm** [comment]
I added two relevant screenshots to indilib ;)

**Comment by knro** [comment]
I'll check, you can also share it here. Each product has some details about it, I was trying to pull this from the website, but it would be nice if you have post a short paragraph about its feature..etc like we do for other drivers.

**Comment by knro** [comment]
@grm is the Mini version also supported using the same drivers?

**Pull request merged**
