### PR TITLE
Version 1.3

### PR DESCRIPTION
**Pull request by azwing**
Dear Jasem,

Thanks for examining the pull request.

### CODE REVIEW

**Comment by knro** [comment]
You'd probably want to remove the .directory entries and KDevelop files from the PR.

**Comment by azwing** [comment]
I must admit I am lost at this point. 
Now I see these .directory but still not the KDevelop files, I have to search.
Should I then restart the whole process.
Sorry I am really a dummie here.

**Comment by knro** [comment]
This is the KDevelop file: libindi.kdev4

Also, you made a change to README which shouldn't be part of this PR as well. It's OK, you can make further commits to this PR to remove these files. No need to restart the process.

**Comment by azwing** [comment]
Dear Jasem,

Thank you.
I learned something again today.

**Comment by knro** [comment]
Next, remove changes to the README file

**Comment by knro** [comment]
what is the OnStep_Sk.xml for? I don't see it getting used anywhere?

**Comment by azwing** [comment]
It was a trial and forgot to remove it.
I remove it right now.

**Comment by azwing** [comment]
I have really no idea what this "error: array used as initializer" comes from.
I had the same idea as you yesterday night but left it to the night to think about.

**Comment by jpaana** [comment]
It's probably from this line in lx200_OnStep.h:
 char oldOSAlignStat[10]="300";
as that is an initialization with a char array, which is only legal in C++11, gcc 4.8 didn't have that yet.

**Comment by azwing** [comment]
Finally it succeded thatnks to the help of Jpaana.
I really have still a lot to read and to learn!

**Pull request merged**
