### PR TITLE
INDI v2.0.0 changes

### PR DESCRIPTION
**Pull request by knro**
Changes required for INDI v2.0.0 package.

### CODE REVIEW

**Comment by knro** [comment]
@pawel-soja Do we need to start removing deprecated interfaces for 2.0.0?

**Comment by pawel-soja** [comment]
You mean `BaseMediator` to remove fragments marked for version 1.x.x? I know that was the intention, but this will force all clients to be updated, including those written in Python. I'm thinking about an additional option when compiling, so that I can use the old interface when there will be an armageddon on the forums about "why it doesn't work for me" - extend the time of reimplementation of clients.

I see that after your changes not all tests/builds pass. You can push changes to branch 2.0.0. officially working on it. I'll try to make the appropriate changes.

**Comment by knro** [comment]
Yes of course it would be nice if we can somehow maintain backward compatibility while issuing deprecation warnings. I'll close this PR for now until you find a better solution to handle backward compabitlity.

**Comment by pawel-soja** [comment]
@knro I am preparing changes, please answer the above questions.

Thanks!

**Comment by knro** [comment]
You mean about maintaining backward compatibility in 2.0.0?

**Comment by pawel-soja** [comment]
Here, my point is that with subsequent versions, you do not have to edit and replace so many files. I am currently making changes and deprecated markings depending on the compiled version. I propose to allow compilation of versions 2 and 1 in the future.

**Comment by knro** [comment]
I see, so the library won't support both at run time, only by compiling it with flags?

**Comment by pawel-soja** [comment]
Yes, for example by changing version 2.0.0 to 1.10.0, you will be able to compile a library compatible with version 1. Now, I would like to understand the changes you made to this pull request.

**Pull request closed without merging**
