### PR TITLE
Compilation fixes

### PR DESCRIPTION
**Pull request by kecsap**

### CODE REVIEW

**Comment by knro** [comment]
probably do not need the one for QHY as I will push an update shortly for SDK v1.0.8

**Comment by knro** [comment]
any of this still required? If yes, please update the PR.

**Comment by kecsap** [comment]
Yes, since the problem was not fixed really, just a temporary. The next QHY SDK update will contain the same problematic header what is currently locally patched.

**Comment by jochym** [comment]
I am not too enthusiastic about switching off warnings instead of fixing the problem... Is this the only way?

**Comment by kecsap** [comment]
@jochym We have to be relaxed for 3rd party components because we don't want to maintain local patching. (And it is not a crucial warning.)

**Pull request merged**
