### PR TITLE
Initial release of Alluna TCS2 Driver

### PR DESCRIPTION
**Pull request by peter-englmaier**
The Telescope-Control-System TCS of ALLUNA Optics, has been designed for the remote control of high-quality telescopes. Alluna Optics  provides only ASCOM drivers and a Windows EXE program to control the  TCS2 Device. The TCS2 can also be controlled by an optional handheld  device. 

The indi driver has been developed by me, Peter Englmaier, and I am  not affiliated with Alluna Optics, but own a small Alluna Telescope  and want to use it with Ekos and other indi software.

With TCS several telescope functions are controlled and monitored:

- Air conditioning of the optical tube and the main mirror i.e., primary/secondary mirror heating and ventilation
- Temperature of ambient (focuser), primary and secondary mirror
- Focusing of the optics
- Control of the optionally available CCD Rotator
- Control of the optionally available robotic Dust Cover
- Setting configuration parameters

As I do not have the rotator option, I have not (yet) implemented that  part. Also some less useful functions are still missing. 

But it is possible, to use the focuser with ekos, control the dust  cover, and the climate settings.

Please let me know, if I need to refactor something. Some parts of the code are cut&paste from other drivers.

### CODE REVIEW

**Comment by peter-englmaier** [comment]
I think I need to add documentation for https://indilib.org/individuals/devices/focusers.html
Please let me know, how I can do that.

**Comment by knro** [comment]
Thank you Peter. Can you please use INDI::PropertyXXX (e.g. INDI::PropertyNumber) instead of the old ISwitch/INumber properties? For the documentation, you can attach a zip file with the documentation + images and we'll upload them to INDI website.

**Comment by peter-englmaier** [comment]
Yes, I can do that. Is the indi the right place for the driver or should I move it to indi-3rdparty? I find focuser drivers in both places.

**Comment by knro** [comment]
Without any external dependencies, it should stay in indi-core.

**Comment by peter-englmaier** [comment]
Ok, I replaced the ISwitch/INumber properties. I think there is no way, to also replace the ones inherited from  INDI::Focuser. 

The code compiles fine, but I have to do some tests within my observatory now. So please do not merge, yet.
Simulation mode was also removed, because it is not implemented.
Anything else I should change?

**Comment by knro** [comment]
This looks great now. Please let us know once you tested the code.

**Comment by peter-englmaier** [comment]
I have tested the code and fixed a bug introduced by the refactoring. Now it seems to work fine. I hope I also fixed the warning about unused variable which made the mac build "break".

**Comment by knro** [comment]
Can you add an entry as well to drivers.xml ?

**Comment by peter-englmaier** [comment]
@knro Ok, I changed the drivers.xml. What is it used for? I had no problem finding and using the driver within kstars.

**Comment by peter-englmaier** [comment]
Thanks for merging my pull request so quickly ;-)

Now, I should follow up on this:
> For the documentation, you can attach a zip file with the documentation + images and we'll upload them to INDI website.

This will take some time to do, so please be patient.

**Comment by peter-englmaier** [comment]
@knro please find here the documentation for the website:
[alluna-indi-docu.zip](https://github.com/indilib/indi/files/14228947/alluna-indi-docu.zip)

**Comment by knro** [comment]
@naheedsa please add above to INDI & StellarMate moset tree

**Pull request merged**
