### PR TITLE
Fix build on non-Linux

### PR DESCRIPTION
**Pull request by sthibaul**

### CODE REVIEW

**Comment by sthibaul** [comment]
(@pinotree for information)

**Comment by knro** [comment]
Thanks, this is related to #1794 so need to wait until that is tested and merged first. Is there any overlap?

**Comment by sthibaul** [comment]
In libs/indiclient/baseclient.cpp, yes, but we used exactly the same fix.

**Comment by knro** [comment]
Please rebase

**Comment by sthibaul** [comment]
Here it is.

**Pull request merged**
