### PR TITLE
Driver for Gemini Snapcap 

### PR DESCRIPTION
**Pull request by jpaana**
This pull request adds driver for Gemini SnapCap (http://www.geminitelescope.com/snapcap-motorized-tube-ota-cap/) motorized OTA cap and flat light. It's mostly the same driver as for Flip Flat but with some serial protocol and behavior differences. The controller is Arduino based and uses the same USB ids as any other Arduino Uno so specific udev rules are unfortunately not possible, but otherwise something like this works:
`SUBSYSTEM=="tty", ATTRS{idVendor}=="2a03", ATTRS{idProduct}=="0043", SYMLINK+="snapcap", ENV{ID_MM_DEVICE_IGNORE}="1"`

Also the current firmware version doesn't provide very good way of identifying the device and whether it has a light or not so I just read the firmware version and assume the device is there if the response looks valid and that it has a light.

### CODE REVIEW

**Comment by knro** [comment]
Thanks! This is great I thought FlipFlat was the only device of its kind available commercially until this. Please fix the travis error and it would be great if you can provide excellent documentation for it like you did before!

**Comment by jpaana** [comment]
Yes, it's good to have more options. I wrote some documentation at http://s2.org/~jpaana/snapcap/ and removed the unused variable so Travis should pass again.

**Comment by jpaana** [comment]
Forgot to mention the controller has built-in bluetooth serial port that can also be used instead of USB cable, added that to the documentation.

**Comment by knro** [comment]
Thanks, I modified the documentation a bit here to clarify more details: http://indilib.org/devices/auxiliary/gemini-snapcap.html

Can you please inform Gemini Telescopes about this driver so that they mention INDI support on their page with a link to the above documentation? Thanks!

**Comment by jpaana** [comment]
Thanks, done :)

**Pull request merged**
