### PR TITLE
WIP: Replace FORCECWUP with TARGETPIERSIDE in eqmod

### PR DESCRIPTION
**Pull request by nadvornik**
This is what I have so far for
https://github.com/indilib/indi/issues/798

I have found that pier side and limits checking on south hemisphere was broken - pier side should not depend on hemisphere.

I have not tested it much yet, I just made it pass the unit tests.

### CODE REVIEW

**Comment by knro** [comment]
Great, thanks! I will try to give this a go tonight if the weather clears up. Anything specific to look for beside checking the pier side?

**Comment by knro** [comment]
@geehalel I know you're busy, but if you have some comment on this, please let us know :-)

**Comment by knro** [comment]
@nadvornik Can you please email me at mutlaqja@ikarustech.com ? Thanks.

**Comment by geehalel** [comment]
Hi,
I remember a discussion some time ago with Patrick resulting in a patch to fix eqmod Side of Pier (see [commit](https://github.com/indilib/indi/commit/ce360adfa417574f6b609100216a6951bd75f0f5)). That was based on the following [paper](https://www.indilib.org/media/kunena/attachments/495/ASCOMSideOfPierBehaviour.pdf) from ASCOM. I also just looked into the Eqmod ASCOM releases notes and see that they have added an option:
`ASCOM setup - option to select pierside method (Pointing, Physical or None)`
I don't know what is currently used in clients (Ekos, PHD2, Linguider, ...) nor how, so you're surely more advised to propose changes than I am. All this seems to be a question of using the same definition for drivers, clients and... users. 
Your above idea to replace FORCECWUP with ALLOWCWUP/TARGETPIERSIDE is indeed more natural, you're right. Furthermore when using alignment you may not know the resulting pierside.
Thanks for correcting pier side and limits checkings in south hemisphere, even not defined, things may be wrong ;-).

**Comment by jpaana** [comment]
Tested this last night, worked nicely.

**Pull request merged**
