### PR TITLE
Streammanager/refactoring - move queue and gamma lut to anothers files

### PR DESCRIPTION
**Pull request by pawel-soja**
Hi!
I am request in another cleaned version of the StreamManager class.

Additionally, I replaced the queue logic from std::list with std::queue (UniqueQueue).
std::list always allocates an extra header to create a node when adding an element.
std::queue is optimized not to allocate every time.

GammaLut16 class, you do not need to watch out to free memory, I try not to use new / delete operators, when the standard library offers its proven solutions for this.

I am trying to make the code more error-tolerant without sacrificing performance.
By the way, it would be nice to do d-pointers for common classes. In particular, shared with Indi 3rd Lib.

### CODE REVIEW

**Comment by pawel-soja** [comment]
oh noo!
I'll take care of this problem, sorry :(

**Comment by knro** [comment]
Thanks! I agree that opaque pointers would help a lot maintaining binary compatibility with 3rd party drivers. We can perhaps do this in steps and check for any possible regressions. I've seen this approach all the time used in Qt libraries, but it was never extended to INDI.

**Comment by lantictac** [comment]
I'm getting a error building on MacOS:

```
FAILED: CMakeFiles/indidriverstatic.dir/libs/stream/streammanager.cpp.o 
/Library/Developer/CommandLineTools/usr/bin/clang++ -DGIT_TAG_STRING=\"v1.8.7-17-g32fdbe8c\" -DHAVE_LIBNOVA -DWITH_ENCLEN -I. -I/Users/willw/Work/KStars/craft-root/download/git/libs/indiserver -I/Users/willw/Work/KStars/craft-root/download/git/libs/indiserver/libs -I/Users/willw/Work/KStars/craft-root/download/git/libs/indiserver/libs/indibase -I/Users/willw/Work/KStars/craft-root/include -I/Users/willw/Work/KStars/craft-root/download/git/libs/indiserver/libs/dsp -I/Users/willw/Work/KStars/craft-root/download/git/libs/indiserver/libs/stream -I/Users/willw/Work/KStars/craft-root/include/libnova -I/Users/willw/Work/KStars/craft-root/include/libusb-1.0 -I/Library/Frameworks/Mono.framework/Headers -fdiagnostics-color=always -std=c++11 -D_FORTIFY_SOURCE=2 -fstack-protector-all -fPIE -O1  -Wall -Wextra -Wno-nonnull -Wno-deprecated-declarations -g -O2 -g -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -fPIC -MD -MT CMakeFiles/indidriverstatic.dir/libs/stream/streammanager.cpp.o -MF CMakeFiles/indidriverstatic.dir/libs/stream/streammanager.cpp.o.d -o CMakeFiles/indidriverstatic.dir/libs/stream/streammanager.cpp.o -c /Users/willw/Work/KStars/craft-root/download/git/libs/indiserver/libs/stream/streammanager.cpp
In file included from /Users/willw/Work/KStars/craft-root/download/git/libs/indiserver/libs/stream/streammanager.cpp:26:
In file included from /Users/willw/Work/KStars/craft-root/download/git/libs/indiserver/libs/stream/streammanager.h:39:
/Users/willw/Work/KStars/craft-root/download/git/libs/indiserver/libs/stream/uniquequeue.h:56:24: error: unknown type name 'uint'; did you mean 'int'?
    bool pop(T & dest, uint msecs);
                       ^~~~
                       int
/Users/willw/Work/KStars/craft-root/download/git/libs/indiserver/libs/stream/uniquequeue.h:68:23: error: unknown type name 'uint'; did you mean 'int'?
    bool waitForEmpty(uint msecs) const;
                      ^~~~
                      int
/Users/willw/Work/KStars/craft-root/download/git/libs/indiserver/libs/stream/uniquequeue.h:120:43: error: unknown type name 'uint'; did you mean 'int'?
inline bool UniqueQueue<T>::pop(T & dest, uint msecs)
                                          ^~~~
                                          int
/Users/willw/Work/KStars/craft-root/download/git/libs/indiserver/libs/stream/uniquequeue.h:160:42: error: unknown type name 'uint'; did you mean 'int'?
inline bool UniqueQueue<T>::waitForEmpty(uint msecs) const
                                         ^~~~
                                         int
4 errors generated.

[143/461] Building CXX object CMakeFiles/indi_planewave_deltat.dir/drivers/auxiliary/planewave_delta.cpp.o
[144/461] Building CXX object CMakeFiles/indidriverstatic.dir/libs/stream/encoder/rawencoder.cpp.o
FAILED: CMakeFiles/indidriverstatic.dir/libs/stream/encoder/rawencoder.cpp.o 
```

**Comment by pawel-soja** [comment]
[Fixed #1284 ](https://github.com/indilib/indi/pull/1284)

**Pull request merged**
