### PR TITLE
Refactor CMakeLists - separation of libraries

### PR DESCRIPTION
**Pull request by pawel-soja**
Split the libraries into separate folders and create `CMakeLists` for each of them.

### CODE REVIEW

**Comment by pawel-soja** [comment]
@knro Do we care about UNITY_BUILD? I see that it has not been tested for a long time and bugs fly. I am also not convinced that UNITY_BUILD is needed with the current capabilities of compilers and multi-threading of compilation.

**Comment by pawel-soja** [comment]
> @knro Do we care about UNITY_BUILD? I see that it has not been tested for a long time and bugs fly. I am also not convinced that UNITY_BUILD is needed with the current capabilities of compilers and multi-threading of compilation.

@knro I repeat the question, can I remove all `UNITY_BUILD`?
https://github.com/indilib/indi/blob/f0228fac9a8b7f30e443d05a6a3cd7e12eb3c1b7/CMakeLists.txt#L448

**Comment by knro** [comment]
Sorry, sure go ahead.

**Comment by pawel-soja** [comment]
There are 2 options for building:
```cmake
OPTION(INDI_BUILD_SHARED "Build shared library" ON)
OPTION(INDI_BUILD_STATIC "Build static library" ON)
```

By default, they are enabled and the following libraries are created:
```
libindiAlignmentClient.a
libindiAlignmentDriver.so -> libindiAlignmentDriver.so.1
libindiAlignmentDriver.so.1 -> libindiAlignmentDriver.so.1.9.9
libindiAlignmentDriver.so.1.9.9

libindiclientqt.a
libindiclientqt.so -> libindiclientqt.so.1
libindiclientqt.so.1 -> libindiclientqt.so.1.9.9
libindiclientqt.so.1.9.9

libindiclient.a
libindiclient.so -> libindiclient.so.1
libindiclient.so.1 -> libindiclient.so.1.9.9
libindiclient.so.1.9.9

libindidriver.a
libindidriver.so -> libindidriver.so.1
libindidriver.so.1 -> libindidriver.so.1.9.9
libindidriver.so.1.9.9

libindilx200.so -> libindilx200.so.1
libindilx200.so.1 -> libindilx200.so.1.9.9
libindilx200.so.1.9.9
```
Shared libraries have been added.
The static libraries have been left with the same name as before.

For the library `libindilx200` I did not add a static library so as not to obscure the name. Because static libraries have priority when linking.

I suggest for the future to make static libraries have `static` in the name for easier selection when linking.
In the Indi version `2.0.0` I will make such libraries appear by default, so that there will be time for a smooth transition in, for example, KStars.

**Comment by pawel-soja** [comment]
@knro  Ready for review.
In this pull request additionally downgraded version for CMakeLists to `3.13` and added Debian Buster for CI.

**Comment by knro** [comment]
Looks like this causes our Launchpad debian builds to [fail](https://launchpadlibrarian.net/636785035/buildlog_ubuntu-jammy-amd64.libindi_1.9.9+202211300739~ubuntu22.04.1_BUILDING.txt.gz). Can you please check? We need an urgent fix.

**Comment by pawel-soja** [comment]
I think I have reproduced the problem. I'll analyze what's going on right now. Later, I will also add a package build to CI for the future.

**Comment by pawel-soja** [comment]
`indiclient.so` never built before, when I added options to build static and shared libraries, by default the shared library is additionally built. From what I can see, other libraries in `INDI Core` want to link it instead of static.

**Comment by pawel-soja** [comment]
Fixed: https://github.com/indilib/indi/pull/1776

**Pull request merged**
