### PR TITLE
initial refactorings on imager agent

### PR DESCRIPTION
**Pull request by GuLinux**
- Improve encapsulation
 - Extract Group into separate file
 - Avoid raw strings
 - Extract utility methods like `currentGroup` and `nextGroup`

### CODE REVIEW

**Comment by knro** [comment]
@polakovic any thoughts?

**Comment by polakovic** [comment]
It looks correct.

**Comment by GuLinux** [comment]
Just some heads up: this is a first step on various refactoring/improvements I'd like to make.
After this, I'd like to extract the sequence steps as well, and (my final goal) also add a few more controls, mainly:
 - Gain setting
 - Some kind of callback support pre/post shot and pre/post group (maybe a "launch script" field?)

**Comment by knro** [comment]
You want to make more changes to the PR or should I merge it?

**Comment by GuLinux** [comment]
I think it would be better to have multiple PRs, in order to have more incremental changes, it's probably even easier for you to review them (plus, I don't really have a lot of free time, so I'm not sure when the next changes will come though)

**Pull request merged**
