### PR TITLE
Sensors

### PR DESCRIPTION
**Pull request by iliaplatone**

### CODE REVIEW

**Comment by iliaplatone** [comment]
@knro please wait before merging, thanks.

**Comment by iliaplatone** [comment]
This can be merged now.

**Comment by iliaplatone** [comment]
There's no problem about baud rates, but I need a way to store high precision timestamps, expecially for correlators and receivers like rtl-sdr and limesdr. Some limesdr devices have separate clock inputs and should require at least sysclock tick timing resolution.
Maybe a custom FIT entry?
Let me know about this please.

**Comment by knro** [comment]
FITS entry would work fine in this case. I presume you don't want high precision timestamp for the logs per se?

**Comment by iliaplatone** [comment]
Perfect! I need them in post-processing. Which keyword should be used?

**Comment by knro** [comment]
Well, I'd leave this up to you. We cannot use DATE-OBS since that is the standard keyword, so anything else is OK. Perhaps they already have some keyword for this in IRAF or other packages?

**Comment by iliaplatone** [comment]
What about DATE? Is it used anywhere else?

**Comment by knro** [comment]
how about TIMESTAMP?

**Comment by iliaplatone** [comment]
Yes, Timestamp is more appropriate, thank you, I made a pull request, please check it out, sorry.

**Pull request merged**
