### PR TITLE
Dspau

### PR DESCRIPTION
**Pull request by iliaplatone**

### CODE REVIEW

**Comment by knro** [comment]
submodules break launchpad builds for some reason last I checked. We have to check now if that's fixed otherwise it will break the whole INDI build.

**Comment by iliaplatone** [comment]
Ok, I'll wait for this. I felt free to do this because of updating issues with dspau, maybe it's good to ensure, if this is possible, to not keep track of the latest commits of submodules, but only stable versions or tags.

**Comment by knro** [comment]
Ok no confirmation so far. Can we do this as is without submodules? Please check #832

**Comment by iliaplatone** [comment]
Yes I'll prepare a new PR asap

**Comment by knro** [comment]
Ok, please open a new PR. Currently, 3rd party is broken until this is fixed :(

**Pull request closed without merging**
