### PR TITLE
Shelyak eShel driver

### PR DESCRIPTION
**Pull request by sholmbo**
Tested and working.

### CODE REVIEW

**Comment by knro** [comment]
Thanks! The driver XML file is missing. Can you also write some details we can put in the INDI devices page with screenshots..etc? Something like this: http://indilib.org/devices/focusers/focuslynx.html

**Comment by jochym** [comment]
It will be also useful if you would add the driver build to .travis.yml - that way your driver will be automatically tested before merging - it builds on pull request.

**Comment by sholmbo** [comment]
@knro I'll look at it, but it won't be as detailed as that example.
@jochym I don't know this Travis-CI. Am I right when I think that I just have to add it to 3rdparty/CMakeLists.txt? By the way, I think line 40 should be `option(WITH_ARDUINO "Install Arduino Driver" On)`, right?

**Comment by jochym** [comment]
@sholmbo Just check if it builds in standard way (the same the other 3rdparty packages build). I will add the build myself to travis.yml

**Pull request merged**
