### PR TITLE
Updated flux calculation for CCD Simulator

### PR DESCRIPTION
**Pull request by TallFurryMan**
This PR updates the flux calculation in the CCD Simulator and refactors the flux calculation into a separate function, where the `k`, affine scale, and `z`, affine offset, are calculated from the limiting and saturation magnitudes so that:
- the limiting magnitude provides zero ADU whatever the exposure
- the saturation magnitude provides max ADU in one second

This PR updates the rendering of stars so that the flux is rendered as a gaussian distribution of unitary integral `1/(sqrt(2pi)*sigma) * exp( -x² / (2*sigma²) )`.

This PR was tested with a rendering of Vega and stars of various magnitudes, and shows a clear improvement compared to the previous calculation. Specifically, the previous calculation produced star centers with the same flux value whatever the seeing/focus and did not account for the dispersion in the gaussian rendering. This PR also makes the Ekos Focus tests more stable and reliable.

### CODE REVIEW

**Comment by TallFurryMan** [comment]
However, in this PR:
- I did not optimise the flux function.
- The gaussian I used for rendering probably has a unitary integral in 1-D, but maybe not in 2-D.
- Test are not passing, they need to be reworked.

This is in the context of #1317.

**Comment by knro** [comment]
Thanks! Any ideas about the failed CI?

**Comment by TallFurryMan** [comment]
Yeah in the test implementation, one star is rendered with controlled parameters, and the result is checked against expected values. Because I changed the flux calculation and the gaussian function used for rendering, I need to modify the assertion values.

**Comment by TallFurryMan** [comment]
I realise the vignetting management also has an issue: subframes get their own vignetting effect, instead of using the effect from the full frame...

image

I'll raise another issue and tackle this in another PR.

**Comment by knro** [comment]
Any update?

**Comment by TallFurryMan** [comment]
This PR is ready as is. I didn't add as many tests as I had planned, but the existing ones cover the star rendering changes.

**Pull request merged**
