### PR TITLE
Tests for the CCD simulator

### PR DESCRIPTION
**Pull request by TallFurryMan**
A few preliminary tests for the CCD simulator.

This was part of an earlier activity to introduce aperture-based PSF star rendering, in order to implement a rough flatness and sensor centering utility for KStars Ekos.

This PR adds property tests, guide API tests and rendering tests. It's nowhere near a complete test plan, but allows to find that:
- Frame buffer is not reset just after setting parameters up.
- RA/DEC fields are undefined after instantiating the driver.

### CODE REVIEW

**Comment by knro** [comment]
Great!! I will give it a go shortly and report back.

**Comment by TallFurryMan** [comment]
Force-updated the PR to allow proper merge. No code change.

**Comment by knro** [comment]
is this still WIP?

**Comment by TallFurryMan** [comment]
Ah no this is final, sorry for not reminding you :)

**Pull request merged**
